- legate/numpy/array.py
- legate/numpy/config.py
- legate/numpy/deferred.py
- legate/numpy/runtime.py
- src/legate_numpy_c.h
- src/proj.cc
- tests/binary_op_broadcast.py
This PR refactors the logic that picks projection functors such that the logic is immune to the chosen maximum number of dimensions. This also cleans up obsolete cases and adds missing ones, including the one that was triggering #10.
> Refactoring for the broadcasting logic

- examples/kmeans.py
- examples/kmeans_slow.py
- examples/kmeans_sort.py
- legate/numpy/deferred.py
This PR fixes a crash that happens in the non-testing mode.
> Bug fix for release mode

- src/search/nonzero.cc
- src/search/nonzero.cu
- src/search/nonzero_omp.cc
- src/search/nonzero_template.inl
This PR is to port the nonzero implementation to the new buffer API.
> Port nozero to the new buffer API

- legate/numpy/deferred.py
This short PR adds a missing constraint for bincount.
> Missing constraint for bincount

- legate/numpy/deferred.py
> Fix legate data interface

- legate/numpy/deferred.py
This PR is to make `dot` handle overlapping stores correctly, which partially addresses #57.
> Handle overlapping stores correctly in dot

- legate/numpy/config.py
- legate/numpy/deferred.py
- legate/numpy/runtime.py
- src/legate_numpy_c.h
This PR is to use the new interface for reduction ops.
> Port to the new reduction op interface

- legate/numpy/deferred.py
This PR is to never use delinearization outside the reshape operator. A consequence is that we now have to make copies for the cases where we simply returned delinearized stores.
> Stop using delinearization

- requirements.txt
We are now using conda env yaml's instead.
> Remove leftover requirements.txt

- cunumeric/runtime.py
This PR removes the obsolete `NumPyAllocation` class.
> Remove NumPyAllocation

- CONTRIBUTING.md
- README.md
> Adding contributions file

- cunumeric/module.py
- tests/array_split.py
- tests/split.py
- split, vsplit, hsplit, dsplit and array_split
- test code to run and compare 'split' and 'array_split' w/ cunumeric and numpy
> Implemented split routines and a test

- cunumeric/coverage.py
- cunumeric/linalg/linalg.py
- cunumeric/module.py
- cunumeric/random/random.py
- docs/cunumeric/source/api/random.rst
- docs/cunumeric/source/comparison/_comparison_generator.py
- docs/cunumeric/source/comparison/comparison.rst
- docs/cunumeric/source/conf.py
- docs/cunumeric/source/index.rst
> adding script for comparing API coverage + table at the documentation page

- api/index.html
> adding redirection for api reference

- src/Makefile
- src/cunumeric.mk
- src/cunumeric/convolution/convolve.cu
- src/cunumeric/convolution/convolve_callbacks.cu
- src/cunumeric/convolution/convolve_common.h
- src/cunumeric/cuda_help.h
- src/cunumeric/cudalibs.cu
- src/cunumeric/cudalibs.h
This PR refactors #140 for the new FFT plan cache and device linking facility.
> Port and refactor GH #140 "Use cufft callbacks for better performance on fft-based convolutions"

- .github/workflows/ci.yml
Add Github context dumps for when something in CI goes wrong.
> CI debugging information

- cunumeric/coverage.py
- cunumeric/module.py
- docs/cunumeric/source/api/_ndarray.rst
- docs/cunumeric/source/api/creation.rst
- docs/cunumeric/source/api/ndarray.rst
- docs/cunumeric/source/api/sorting.rst
- docs/cunumeric/source/comparison/_comparison_generator.py
This PR forward ports two late fixes that were made after `22.05` was branched:
* https://github.com/nv-legate/cunumeric/commit/7738798d47bc6e741095e05e683846cea94e99bb from #239 
* https://github.com/nv-legate/cunumeric/commit/9e829368cacfdc35210267288efebdd6c186aa0e from #240
cc @magnatelee
> Forward port late commits from 22.03

- src/cunumeric/matrix/matvecmul.cu
This PR is to use the cuBLAS version at runtime to activate the workaround for a known matrix-vector multiplication bug in cuBLAS. Previously, the workaround was guarded by a macro, which works only when cuNumeric was built from source on the target environment.
> Activate the cuBLAS workaround by checking the cuBLAS version at runtime

- src/Makefile
Co-authored-by: Marcin Zalewski <mzalewski@nvidia.com>
> Release v22.03.00-package-fix

- docs/cunumeric/source/comparison/comparison.rst
> Add user-facing docs for coverage reporting

- docs/cunumeric/source/comparison/compare_by_category.py
@magnatelee I thought we might want to keep the script in the repo
> creating script for calculating API coverage by categories

- src/cunumeric/nullary/window_util.h
> Don't use constexpr for window functions

- tests/unit/cunumeric/test_config.py
A unit test had gotten out of sync after recent PR merges.
> Unit test fixups

- .github/workflows/ci.yml
- test.py
- tests/unit/cunumeric/test_config.py
- tests/unit/cunumeric/test_coverage.py
- tests/unit/cunumeric/test_patch.py
- tests/unit/cunumeric/test_utils.py
Use `--unit` flag to run unit tests.
> Add unit tests to `test.py`

- test.py
> Don't dump test stdout unconditionally

- cunumeric/deferred.py
- src/cunumeric/index/zip.cc
- src/cunumeric/index/zip.cu
- src/cunumeric/index/zip.h
- src/cunumeric/index/zip_omp.cc
- src/cunumeric/index/zip_template.inl
- tests/integration/test_advanced_indexing.py
Addresses issue https://github.com/nv-legate/cunumeric/issues/320
> adding support for negative indices in advanced indexing

- conda/environment-test-3.10.yml
- conda/environment-test-3.8.yml
- conda/environment-test-3.9.yml
cc @manopapad @magnatelee @marcinz @m3vaz 
@manopapad asked if I might make a first stab at splitting out the env files as I described earlier. This PR splits out the current single conda env dev file into per-python version files:
```
environment-test-3.8.yml
environment-test-3.9.yml
environment-test-3.10.yml
```
These are  "kitchen sink" env files, that should usable for any dev who wants to install, run tests, and build docs locally. I think these are immediately useful to devs in order to create per-python dev environments easily. 
I think the commented groupings in these files represent the usage of the various dependencies, but please provide any feedback. 
So then the question is what further refinements or splits might be useful for CI? Some ideas:
* an `environment-build.yml` …
> Discussion PR for conda envs split

- conda/conda-build/build.sh
- conda/conda-build/conda_build_config.yaml
- conda/conda-build/meta.yaml
- install.py
Ongoing work on conda recipes (update PR description before merging).
> [WIP] Conda recipes improvements

- cunumeric/_sphinxext/__init__.py
- cunumeric/_sphinxext/comparison_table.py
- cunumeric/_sphinxext/ufunc_formatter.py
- cunumeric/module.py
- docs/cunumeric/source/api/_ndarray.rst
- docs/cunumeric/source/api/indexing.rst
- docs/cunumeric/source/api/ndarray.rst
- docs/cunumeric/source/comparison/comparison.rst
- docs/cunumeric/source/conf.py
This PR:
* Adds a docs section for `lgpatch`
* Removes an unneeded JS file add in `conf.py`
* Fixed breakage due to recent API additions
---
> lgpatch docs + doc fixups

- cunumeric/eager.py
- cunumeric/linalg/linalg.py
- cunumeric/module.py
- tests/integration/test_multi_dot.py
Including some fixes for bugs uncovered while testing this.
Will require https://github.com/nv-legate/cunumeric/pull/357 (or something equivalent) before `tests/integration/test_multi_dot.py` will pass.
> Implement multi_dot

- examples/cg.py
- examples/einsum.py
- examples/jacobi.py
- examples/logreg.py
- examples/stencil.py
#373 broke the integration test but it wasn't caught as the CI wasn't running the example programs. This PR is to fix the offending examples so they pass the test.
> Make the example programs pass the CI

- cunumeric/eager.py
- cunumeric/linalg/__init__.py
- cunumeric/linalg/cholesky.py
- cunumeric/linalg/exception.py
- src/cunumeric/matrix/potrf.cc
- src/cunumeric/matrix/potrf.cu
- src/cunumeric/matrix/potrf_omp.cc
This PR is to correctly raise a Python exception from `cunumeric.linalg.cholesky` when the input matrix is not positive definite, using the new exception support in the core.
> Proper exception handling for cholesky

- install.py
- setup.py
cuNumeric equivalent to https://github.com/nv-legate/legate.core/pull/263
> Fixes for building with setup.py outside conda, primarily Mac

- conda/conda-build/meta.yaml
* Add requirement for our minimum supported NumPy version
* Add runtime dependency on minimum CTK version
> Cherry pick: Update conda requirements (#383)

- cunumeric/random/random.py
> Make the NumPy fallback work correctly in `randint`

- cunumeric/array.py
- cunumeric/deferred.py
- cunumeric/eager.py
- cunumeric/runtime.py
- tests/integration/test_squeeze.py
> Squeeze fix

- cunumeric/array.py
- cunumeric/deferred.py
- cunumeric/eager.py
- cunumeric/thunk.py
This PR fixes two minor bugs in the indexing routines
> Minor fix for indexing routines

- tests/integration/test_unary_ufunc.py
This reverts commit 29b060663f3c539fc48e8e6fe09147fb06d48407.
> Revert "Fix reciprocal tests for zero values and improve test value customization (#467)

- tests/integration/test_unary_ufunc.py
* fix reciprocal tests and add unary test customization
* make tests deterministic and enforce root inputs are non-negative
> Fix reciprocal tests for zero values and improve test value customization (#467)

- src/cunumeric/cudalibs.cu
> Make reduced-precision cuBLAS mode opt-in (#519)

- cunumeric/eager.py
- src/cunumeric/unary/convert_util.h
- tests/integration/test_astype.py
> Fix buggy complex-to-bool conversions and add correctness tests for `astype`

- README.md
- cunumeric_cpp.cmake
- install.py
Companion to https://github.com/nv-legate/legate.core/pull/384
> Support building with GASNet-Ex and MPI backends

- docs/cunumeric/source/index.rst
- docs/cunumeric/source/versions.rst
Adding a new version and updating index.rst file
> updating documentation

- src/cunumeric/unary/unary_op_util.h
> Fix a compiler warning

- tests/integration/test_mask_indices.py
- tests/integration/test_moveaxis.py
* Enhance mask_indices and move_axis
* Address comments.
> Enhance mask_indices and move_axis (#622)

- .github/workflows/ci.yml
> Run CI every 4 hours

- .github/workflows/ci.yml
Fix the minutes (run only once), and change to every 6 hours.
> Adjust the schedule of the CI runs

- tests/integration/test_tri.py
- tests/integration/test_trilu.py
- tests/integration/test_trilu_indices.py
- tests/integration/utils/utils.py
> Enhance test_tri*.py.

- src/cunumeric/binary/binary_op_util.h
- src/cunumeric/omp_help.h
- src/cunumeric/scan/scan_local_template.inl
- src/cunumeric/unary/convert_template.inl
- src/cunumeric/unary/convert_util.h
- src/cunumeric/unary/unary_op_util.h
- src/cunumeric/unary/unary_red_util.h
Two QOL changes:
* Catching up the predicate change from https://github.com/nv-legate/legate.core/pull/458
* Making sure `ThreadLocalStorage` can be used for values bigger than 64B
> Some quality-of-life changes

- cunumeric/array.py
- tests/integration/test_compress.py
- tests/integration/test_extract.py
add test case for test_compress.py
> add test case for test_compress.py and test_extract.py

- cunumeric/array.py
- tests/integration/test_data_interface.py
> Handle complex dtypes in __legate_data_interface__

- tests/integration/test_astype.py
- tests/integration/test_convolve.py
add negative test case for test_convolve.py
> add negative test case for test_convolve.py and test_astype.py

- cunumeric/module.py
> More argument checks for `bincount`

- BUILD.md
- README.md
> Clean up the basic build instructions

- tests/integration/test_dot.py
- tests/integration/test_inner.py
- tests/integration/test_tensordot.py
Besides test_inner.py and test_tensordot.py, also fix typo in test_dot.py
> Enhance test_inner.py and test_tensordot.py

- tests/unit/cunumeric/test_config.py
Not sure if an API changed or I was accidentally using a private API. This should fix the currently failing unit test
> fix assertion in config test

- conda/conda-build/build.sh
Co-authored-by: Marcin Zalewski <mzalewski@nvidia.com>
> Update the architectures built in conda package (backport #770)

- conda/conda-build/build.sh
This reverts commit da3319799e5676d6375db8a6b4dd774fc016a5ac.
> Revert "Update the architectures built in conda package (#770) (#771)"

- src/cunumeric/matrix/util.cc
This PR fixes a compilation issue introduced by #811.
> Fix a compilation issue introduced by 811

- .gitignore
- CMakeLists.txt
- cmake/thirdparty/get_legate_core.cmake
- cmake/versions.json
We'll have to merge this after https://github.com/nv-legate/legate.core/pull/593 and update the sha.
> Pin legate to a specific commit

- BUILD.md
> Update BUILD.md (#831)

- docs/cunumeric/source/user/usage.rst
Some changes requested by Shriram
* note reagarding plain python being a quick on-ramp, and emphasizing `legate` driver needed for full features
* clearer emphasis for  "zero-code change" heading -> *Running Numpy programs without changes*
> Update python usage notes

- cmake/versions.json
- src/cunumeric/index/advanced_indexing_template.inl
- src/cunumeric/index/repeat_template.inl
- src/cunumeric/mapper.cc
- src/cunumeric/scan/scan_local_template.inl
- src/cunumeric/search/argwhere_template.inl
- src/cunumeric/search/nonzero_template.inl
- src/cunumeric/set/unique.cu
- src/cunumeric/sort/sort.cu
- src/cunumeric/sort/sort_cpu.inl
This is a companion to https://github.com/nv-legate/legate.core/pull/627.
> Catch up name changes in the API

- tests/integration/test_prod.py
- tests/integration/test_reduction.py
test_prod & test_reduce use allclose to compare float arrays
>  test_prod & test_reduce use allclose to compare float arrays 

- cmake/versions.json
- cunumeric/config.py
- src/cunumeric/cunumeric.cc
- src/cunumeric/cunumeric.h
- tests/unit/cunumeric/test_config.py
This is a companion to https://github.com/nv-legate/legate.core/pull/675 containing changes necessary to be compatible with the new registration API.
> Changes for the new registration API

- cmake/versions.json
- src/cunumeric/arg.cc
- src/cunumeric/cunumeric.cc
- src/cunumeric/cunumeric.cu
This PR is to catch up changes in https://github.com/nv-legate/legate.core/pull/690
> Start using `LibraryContext*`

- cunumeric/coverage.py
- cunumeric/deferred.py
Companion PR to https://github.com/nv-legate/legate.core/pull/707
> Update for Context-less annotations

- src/cunumeric/unary/unary_red.cu
Corry Perry suggested this fix for error we see on GH architecture. All tests pass now.
> fixing cuda error

- src/cunumeric/arg.inl
> Change arg to LLONG_MIN to make it consistent with python.

- cunumeric/random/generator.py
- tests/integration/test_random_advanced.py
- tests/integration/test_random_beta.py
- tests/integration/test_random_bitgenerator.py
- tests/integration/test_random_creation.py
- tests/integration/test_random_gamma.py
- tests/integration/test_random_straightforward.py
- Cover size/shape code path in bitgenerator methods.
- Add some negative tests.
- Minor test bug fix.
> improve random bitgenerator code coverage

- cunumeric/deferred.py
> Missing alignment on histogram call

- conda/conda-build/meta.yaml
Backport #998 from `branch-23.07`.
> pin cuda-version

- .gitignore
PR to add `.legate-test-last-failed` to `.gitignore` to prevent accidental commit
> Ignore last-failed file

- cunumeric/array.py
- cunumeric/module.py
- cunumeric/utils.py
- tests/integration/test_prod.py
- tests/integration/test_reduction.py
- tests/integration/test_squeeze.py
- tests/unit/cunumeric/test_coverage.py
Cunumeric counterpart to https://github.com/nv-legate/legate.core/pull/848
> Satisfy new flake8 type check rules

- .github/workflows/gh-build.yml
- cmake/versions.json
- continuous_integration/scripts/test-cunumeric
- tests/integration/test_overlap.py
Also bump the legate.core version to TOT.
> Update cuda version to 12.2 

- cunumeric/module.py
- docs/cunumeric/source/api/statistics.rst
- tests/integration/test_file.py
- tests/integration/test_nanpercentiles.py
- tests/integration/test_nanquantiles.py
Handling NaNs in quantile and percentile. See https://jirasw.nvidia.com/browse/CNM-554
> Nanquantile, Nanpercentile implementation
