legate/numpy/deferred.py
legate/numpy/runtime.py
src/legate_numpy_c.h
src/shard.cc

Partition the output vector of a GEMV following the non-reduced dimension of the matrix (e.g. if `M` is partitioned into 5x3 tiles, partition `x = Mv` into 5 tiles).
Shard the SumRadix tasks that build the output vector of a GEMV like a 1d launch, considering only the non-reduced dimension of the matrix (e.g. shard the SumRadix 5x3 launch space above like a 1d 5-wide launch space).
If multiple arrays on a binary operation have a launch space, pick the smallest one. This is meant to capture the case where the output `x` of a GEMV goes through some vector-vector operations before being used as the input to another GEMV. In this case `x` is partitioned over a smaller color space, and switching to the full color space would mean repartitioning, that we would prefer to avoid until we get to …

Improved partitioning and sharding for GEMV

---

legate/numpy/deferred.py

This short PR is to add missing alignment constraints for matrix-vector multiplication.

Add missing alignment constraints for matrix-vector multiplication

---

src/mapper.cc

This short PR is to make the mapper not alter the GC priority for external instances (which is a no-op). Note that this PR should be ported over once the mapper is rewritten in the  Legate mapping API that is being designed now.

Don't alter the GC priority for external instances

---

examples/gemm.py
examples/kmeans_slow.py
examples/kmeans_sort.py
examples/linreg.py
examples/logreg.py
examples/lstm_backward.py
examples/lstm_forward.py
examples/lstm_full.py
examples/stencil.py
examples/wgrad.py

In multiple occasions the previous behavior of falling back to
vanilla NumPy on ImportError has masked errors in the configuration,
where legate.numpy was really not working, but there was no
indication of this when running the examples.

Be strict when importing legate.numpy in examples

---

src/scalar.cc
src/scalar.h

It turns out that I was still living in the stone age and writing code illegal in the modern C++. This PR is to fix those errors I found in the untyped scalar implementation.

Fix for reinterpret casts that are actually unsafe in the modern c++

---

src/mapper.h

This fixes the bug that assigned a return type to the function that returned nothing. This simple mistake actually led to a rather spectacular crash (the crash blew up the whole stack and there's no clue whatsoever on what caused it). I suspect the compiler was doing some wild optimizations for inline functions under the assumption that they are faithful to their signatures. I'm leaving this note so that others won't repeat the same mistake as I did.

Remove the return type of the void-returning function in the mapper

---

src/binary/binary_op_util.h
src/unary/unary_op_util.h

#99a18d8 was breaking a bunch of CI tests, and this is an attempt to fix it. Until we find a way to use `fabs` with complex numbers on Mac, we disable the complex operators that rely on it if Clang is being used.

Disable absolute and allcose for complex types only with Clang

---

legate/numpy/deferred.py
tests/reshape.py

This PR is to generalize the `reshape` implementation. The new implementation can handle all kinds of reshaping requests, with a caveat that it makes a copy for some of the requests, specifically those that involve a linearization or a rehashing of the input (e.g., `(5, 4, 10) -> (10, 20)`.

Generalize the reshape operator

---

legate/numpy/deferred.py
src/matrix/dot.cc
src/matrix/dot.cu
src/matrix/dot_omp.cc
src/matrix/dot_template.inl
tests/matrix_mul.py
tests/matrix_vec.py

This PR is to use 32-bit accumulator in dot products for half precision floating numbers. This also includes changes to use dot product for degenerate cases of matrix-matrix and matrix-vector products.

Improve dot product for half precision floats

---

legate/numpy/array.py
legate/numpy/deferred.py
legate/numpy/module.py
tests/tensordot.py

This PR includes changes to support `tensordot`. As stated in the comment,  the added `tensordot` code is exactly the same as that in the canonical numpy, thanks to the generalized `reshape` implementation.

Support for tensordot

---

src/matrix/dot.cu

This PR adds missing type casts to the GPU variant of `dot`.

Add missing type casts for __half

---

.github/workflows/ci.yml

If the branch name matches the target repo in a pull request, pull the image for the same branch from the Core repository. If the branch name does not match the target branch, generate a label consisting of the fork repo owner and the branch name, and use it to look up the corresponding label for core.

Pull the correct Core image

---

src/matrix/matmul_template.inl
src/matrix/matvecmul_template.inl

There was a bug in matrix ops that tries to allocate a really big buffer when the input shape was empty. This PR is to fix that bug.

Emptiness checks for matrix ops

---

src/cunumeric/stat/bincount.cu

This PR replaces `atomicAdd` used in the bincount kernel with Legion's built-in sum reduction op that supports old architectures.

Use built-in reduction op

---

src/cunumeric.mk
src/cunumeric/cuda_help.h
src/cunumeric/cudalibs.cc
src/cunumeric/cudalibs.h
src/cunumeric/cunumeric.cu
src/cunumeric/matrix/matmul.cu
src/cunumeric/matrix/matvecmul.cu

This PR is to start managing CUDA library contexts within cuNumeric. The code that manages cuFFT plans isn't refactored yet, but will later be incorporated in this mechanism once we start working on the fft submodule.

Managing CUDA library contexts directly in cuNumeric

---

src/cunumeric/cudalibs.cc

The environment variable name should have been prefixed with `CUNUMERIC` and not `LEGATE`.

Minor fix for typo

---

src/cunumeric.mk
src/cunumeric/cuda_help.h
src/cunumeric/cudalibs.cu
src/cunumeric/cudalibs.h
src/cunumeric/cunumeric.cu

This PR is to put the CUDA library management code in a .cu file instead of a .cc file. We've been going headerless for CUDA library handles to avoid duplicate definitions of the half float type in a .cc file, but this trick won't work for cuTENSOR whose handle is a struct with a fixed size array instead of just a pointer. So, we use .cu instead so that we can include CUDA library headers in this code.

Use .cu for CUDA library management

---

src/cunumeric/unary/unary_red.cu
tests/reduction_axis.py

The linearization logic was wrong, causing threads to sometimes reduce into the wrong output index, in the case where the reduction collapsed the last axis.
The problematic case was not exercised in the old test because the shape of the input array would never get partitioned in a way that would trigger the issue (at least when running on 2 processors).

Fix slot calculation in reduction kernel

---

install.py

This change would prevent OpenBLAS from running tests during compilation. This is needed when building on machines or in conditions (e.g., using docker) that cause some of the OpenBLAS tests to fail. The potential downside of this is that we would want to run with OpenBLAS checks by default when users are building in the same environment in which they will run. If we want to run OpenBLAS tests by default, we could add an option to prevent testing at build time.

Build OpenBLAS with CROSS option to prevent tests at compile time

---

cunumeric/array.py
cunumeric/deferred.py
cunumeric/eager.py
examples/cholesky.py

This PR add an internal switch to `ndarray.cholesky` to bypass the `tril` call on Cholesky outputs. This allows the Cholesky benchmark to measure performance of the implemented Cholesky factorization more easily.

Add a switch to not call tril on Cholesky outputs

---

tests/array_split.py

Refined this test w/ reduced input shapes. 
Instead, more essential test cases are included w/ empty, singleton arrays

Refined 'tests/array_split.py' w/ more essential input shapes

---

docs/cunumeric/source/comparison/_comparison_generator.py
docs/cunumeric/source/conf.py

We need to exclude config.py and _comparison* script files from pre-commit configuration. 
Pre-commit complains on the order of "import"  in config.py, but the order has to be the way it is for generating correct comparison table

excluding 2 documentation files from pre-commit config file

---

cunumeric/array.py
cunumeric/module.py
tests/append.py
tests/concatenate_stack.py
tests/flatten.py

Append is easily able to be mapped to `concatenate`
In cunumeric, `flatten` is the same as `ravel`
Added tests for each routine. Refined `concatenate` in the previous PR for append.
Currently, we don't support `order = K` in `flatten` and `ravel`, which should be a separate PR for relevent routines (copy, ravel, flatten, etc)

np.append & ndarray.flatten

---

.gitignore
cunumeric/array.py

This PR adds docstrings to `ndarray` methods to match the documentation structure of the official Numpy docs:
https://numpy.org/doc/stable/reference/arrays.ndarray.html
A few notes:
* `cholesky` and `convolve` do not have direct counterparts, I wanted to solicit guidance on content before authoring any docs for these
* Did not add docstrings for funcs that are `NotImplementedError` e.g. `getfield` and `setfield`

Add docstrings to ndarray methods

---

src/cunumeric/matrix/dot_omp.cc
src/cunumeric/omp_help.h
src/cunumeric/search/nonzero_omp.cc
src/cunumeric/unary/scalar_unary_red_omp.cc

This PR replaces all uses of `alloca` in OpenMP tasks with a custom thread local storage implementation that avoids false sharing.

Stop using alloca

---

cunumeric/deferred.py
cunumeric/linalg/cholesky.py
src/cunumeric/mapper.cc
src/cunumeric/matrix/trilu.cc
src/cunumeric/matrix/trilu.cu
src/cunumeric/matrix/trilu_omp.cc
src/cunumeric/matrix/trilu_template.inl
src/cunumeric/pitches.h

This PR contains changes to optimize the `np.tril` operation done as the post-processing in Cholesky. The `Pitches` template now supports a mode where points are visited in Fortran order, which is useful when the instance has fortran layout (the case with Cholesky).

Optimize np.tril used in Cholesky

---

src/cunumeric/arg.inl
src/cunumeric/divmod.h
src/cunumeric/random/philox.h
src/cunumeric/random/rand_util.h

Found using -Wold-style-cast
Following Google C++ Style Guide, arithmetic upcasting replaced with
`type{val}`, arithmetic downcasting replaced with `static_cast<type>(val)`

Remove old-style casts

---

cunumeric/patch.py

This PR adds a *very* basic `cunumeric.patch` module that can be imported early in a script to "automatically" replace NumPy with cuNumeric. With the following example script:
```python
import cunumeric.patch
import numpy as np
a = np.random.randn(4, 5)
np.argmin(a, axis=0)
np.argmin(a, axis=1)
np.argmax(a, axis=0)
np.argmax(a, axis=1)
```
The desired coverage results are generated:
```sh
~/work/cunumeric branch-22.03*
legate37 ❯ legate /tmp/foo.py  -cunumeric:report:coverage 
cuNumeric API coverage: 5/5 (100.0%)
```
* This is not yet quite "zero-change", but is a necessary start, and can be utilized immediately, with one line of code added. Assuming a `-m` option is implemented in legion in the future, the it should become possible to utilized this via the command line:
```
legate -m …
```

Add basic cunumeric.patch module

---

cunumeric/array.py
docs/cunumeric/source/api/math.rst
docs/cunumeric/source/api/ndarray.rst
docs/cunumeric/source/comparison/_comparison_generator.py

Some functions were added without docstrings and/or added without adding to the relevant Sphinx ReST file. Additionally there are a few numpy methods that are not present in our API (see comment below). Finally, there is still a placeholder section in the array methods page for things that don't seem to have a counterpart in the numpy array docs page. We just need to decide where they go:
cc @magnatelee

Fix some docs breakage

---

cunumeric/__init__.py
cunumeric/array.py
cunumeric/coverage.py
cunumeric/linalg/__init__.py
cunumeric/random/__init__.py
cunumeric/runtime.py
cunumeric/utils.py

This PR cleans up and generalizes the existing code for reporting implemented vs unimplemented Numpy API. The updated reporting code is extended to also cover `cunumeric.ndarray`.  
For the invocation
```
LEGATE_TEST=1 legate tests/dot.py --gpus 2 -cunumeric:test -cunumeric:report:coverage  -cunumeric:report:dump-csv /tmp/dot.csv
``` 
The coverage summary is
```
cuNumeric API coverage: 26/26 (100.0%)
```
with CSV:
```
numpy.array,tests/dot.py:27,True
numpy.ndarray.__init__,tests/dot.py:27,True
numpy.array,tests/dot.py:28,True
numpy.ndarray.__init__,tests/dot.py:28,True
numpy.ndarray.dot,tests/dot.py:31,True
numpy.ndarray.__init__,tests/dot.py:31,True
numpy.allclose,tests/dot.py:33,True
numpy.ndarray.__init__,tests/dot.py:33,True
numpy.ndarray._maybe_convert,tests/dot.py:33,True …
```

Expand coverage reporting to ndarray methods

---

cunumeric/coverage.py

This is a focused hotfix PR for the bug discovered and fixed in #229 in case it is preferable to merge a smaller PR for now. cc @magnatelee

Fix trailing comma tuple bug

---

setup.py

I suspect this is the issue behind the reported missing `cunumeric.ufunc` module in the built package testing. I have not located docs on how the release packages are built, so I have not been able to verify that this is a complete solution, but I wanted to have a PR ready to go, in case. cc @magnatelee 
It's possible `setuptools.find_packages` could be used to avoid the need to curate this list manually.

Add cunumeric.ufunc to packages

---

cunumeric/coverage.py
cunumeric/module.py
docs/cunumeric/source/api/_ndarray.rst
docs/cunumeric/source/api/creation.rst
docs/cunumeric/source/api/ndarray.rst
docs/cunumeric/source/api/sorting.rst
docs/cunumeric/source/comparison/_comparison_generator.py

This PR fixes the docs breakage that was uncovered by the fix in #230 
TLDR; The #230 bug caused all the *unimplemented* functions to be erroneously cloned as a tuple `(func,)` instead of `func`. This in turn caused the `autosummary` directive for `ndarray` to ignore them. Howevever *after* #230, the `autosummary` directive for `ndarray` picked the up, and wanted to generate references for them in the class TOC. These are *broken* references, because we do not document *unimplemented* (i.e. numpy-only) functions in our docs. 
This PR removes the `autosummary` directive for `ndarray` and replaces it with a hand-curated TOC. I suppose we could dispense with the class TOC altogether, but Numpy does have a class TOC ([ref](https://numpy.org/doc/1.22/reference/generated/numpy.ndarray.html#numpy …

Fix docs breakage

---

cunumeric/coverage.py

This fixes the issue with ufuncs not being considered in the coverage reports, and also fixed them being missing from the comarison table:
```
legate37 ❯ cat foo.py 
import cunumeric as np
a = np.ndarray([1,2])
np.arccos(a)
~/work/cunumeric bryanv/ufunc_coverage*
legate37 ❯ legate foo.py --gpus 2 -cunumeric:report:coverage -cunumeric:report:dump-csv out.csv
cuNumeric API coverage: 3/3 (100.0%)
~/work/cunumeric bryanv/ufunc_coverage*
legate37 ❯ cat out.csv 
function_name,location,implemented
numpy.ndarray.__init__,foo.py:3,True
numpy.arccos,foo.py:4,True
numpy.ndarray.__init__,foo.py:4,True
```

Fix coverage for ufuncs

---

src/cunumeric/matrix/matvecmul.cu

This PR is to use the cuBLAS version at runtime to activate the workaround for a known matrix-vector multiplication bug in cuBLAS. Previously, the workaround was guarded by a macro, which works only when cuNumeric was built from source on the target environment.

Activate the cuBLAS workaround by checking the cuBLAS version at runtime (ported to 22.05)

---

cunumeric/sort.py
src/cunumeric/sort/sort_template.inl

This is a small bugfix that allows shapes greater int32 range for sort.

fix large shape >int32

---

cunumeric/_ufunc/ufunc.py
cunumeric/array.py

This PR is to clean up some of the `ndarray`'s special methods by replacing their bodies with ufunc invocations.

Use ufuncs in special methods

---

cunumeric/_ufunc/ufunc.py
tests/binary_op_typing.py

This PR makes binary ufuncs' output types consistent with those in NumPy for a subset of cases.

Revise type coercion

---

cunumeric/deferred.py
cunumeric/runtime.py
src/cunumeric/index/repeat.cc
src/cunumeric/index/repeat.cu
src/cunumeric/index/repeat_omp.cc
src/cunumeric/index/repeat_template.inl
src/cunumeric/search/nonzero_template.inl
src/cunumeric/set/unique_reduce_template.inl
src/cunumeric/set/unique_template.inl
src/cunumeric/sort/sort.cu
tests/index_routines.py
tests/repeat.py

This PR updates operator implementations using unbound stores to be compliant with the new unbound store API. This also extends the `repeat` implementation to support N-D cases.

Updates for using the new unbound store API

---

conda/cunumeric_dev.yml
cunumeric/_ufunc/ufunc.py
cunumeric/array.py
cunumeric/coverage.py
cunumeric/deferred.py
cunumeric/eager.py
cunumeric/module.py
cunumeric/runtime.py
cunumeric/thunk.py
cunumeric/utils.py
pyproject.toml
tests/unit/cunumeric/test_utils.py

This PR is a bit of a grab bag of minor things:
* moved helpers  `broadcast_shapes` and `is_advanced_indexing` to `utils` and put under test
* removed unused cruft `_output_float_dtype`
* use `abstractproperty` on where applicable on an ABC
* made wrapping handled consistenty in `coverage`
* enabled type annotations for `coverage` and `utils`

Some misc tests and types

---

docs/cunumeric/source/comparison/_comparison_generator.py

fixed #226 
This is a quick fix for the functions that were missing from the comparison table. Note that for whatever reason, intersphinx references for these functions do not exist (i.e. they are omitted from the numpy docs site). That's the proximate reason they were added to the blocklist. The current PR just renders those entries in the code font:
I would like to overhaul the comparison generation in general, and move it to a sphinx extension. But that will be a larger issue I will submit for consideration.

add missing comparison functions

---

src/cunumeric/search/nonzero_template.inl

The `nonzero` task was using the input element type when creating an empty buffer to return. This PR fixes that bug.

Fix nonzero

---

examples/cg.py
examples/jacobi.py
examples/logreg.py
examples/stencil.py

This PR updates some examples programs to make them use `legate.timing` and also report more accurate steady state timing.

Update example programs

---

conda/cunumeric_dev.yml
cunumeric/eager.py

This PR bumps up the minimum NumPy version to 1.22 and removes code that becomes obsolete due to that change.

Bump up NumPy version

---

cunumeric/array.py
src/cunumeric/mapper.cc
src/cunumeric/sort/sort.cc
src/cunumeric/sort/sort_omp.cc
tests/sort.py

I noticed that cunumeric.ndarray.argsort returns the result in-place while numpy returns a copy. I adjusted the behavior and added a testcase.

fix return value of ndarray.argsort

---

tests/partition.py

in order to reduce test duration some redundant testcases have been removed

reduce testcases for partition test

---

cunumeric/array.py
cunumeric/deferred.py
cunumeric/utils.py
tests/integration/test_trace.py

This PR updates and moves the `trace.py` test that missed #297 
This PR also fixes a few warning conditions that were being reported at the end of pytest runs

Update trace.py tests / fix some warnings

---

cunumeric/sphinxext/__init__.py
cunumeric/sphinxext/ufunc_formatter.py
docs/cunumeric/source/comparison/_comparison_generator.py
docs/cunumeric/source/conf.py

This PR fixes #313 
With these changes the ufunc docs render with appropriate signatures:
For anyone curious: The reason the default `FunctionDocumenter` does get selected is that the `can_document_member` predicate tries to be too clever and ultimately calls
```
return inspect.isfunction(unwrap_all(obj))
``` 
The too-clever part is the `unwrap_all` which tries to see the object is a wrapper of some sort, and then make sure the thing wrapped is a function. In our case the wrapped thing is a `ufunc`. Although it is a callable object, it's not technically a function, so it gets rejected. Subesequntly the generic `DataDocumenter` for module attributes is used. This PR adds a higher priority subclass of `FunctionDocumenter` with a `can_document_member` predicate that recognizes our ufuncs.

Add a custom autodoc class for ufuncs

---

cunumeric/coverage.py

Reverts a previous change to use global `runtime.report_coverage` that broke some unit tests (but tests were apparently not running in CI at the time) Passing the parameter is better for testing so that method was restored.
```
legate37 ❯ legate tests/unit/cunumeric/test_coverage.py             
=============================== test session starts ===============================
platform linux -- Python 3.7.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/bryan/work/cunumeric, configfile: pyproject.toml
plugins: cov-3.0.0
collected 19 items                                                                
tests/unit/cunumeric/test_coverage.py ...................                   [100%]
=============================== 19 passed in 0.08s ================================
```

Pass reporting explicity to coverage decorators

---

src/cunumeric/binary/binary_op.cu
src/cunumeric/binary/binary_red.cu
src/cunumeric/cuda_help.h
src/cunumeric/index/choose.cu
src/cunumeric/index/repeat.cu
src/cunumeric/index/zip.cu
src/cunumeric/matrix/trilu.cu
src/cunumeric/nullary/fill.cu
src/cunumeric/random/rand.cu
src/cunumeric/ternary/where.cu
src/cunumeric/transform/flip.cu
src/cunumeric/unary/convert.cu
src/cunumeric/unary/unary_op.cu

All CUDA kernels were computing global thread ids incorrectly due to integer overflow with 32-bit geometry field values. This PR fixes the issue.

Use 64-bit integers for global thread ids

---

cunumeric/coverage.py
cunumeric/linalg/cholesky.py
cunumeric/runtime.py
tests/unit/cunumeric/test_coverage.py

This PR builds on https://github.com/nv-legate/legate.core/pull/232 to apply centralized argument parsing to `cunumeric`.
Questions:
* Is moving command line configs to `runtime.args` acceptable, or is there a better name (runtime.config)?

Use legate.core arg parsing

---

src/cunumeric/unary/unary_op_util.h
tests/integration/test_unary_ufunc.py

It turns out built-in operators don't do what I expect them to do but silently promote result types, which makes it incorrect to use `decltype(auto)` all the time. This PR is to use correct return types for the unary ops relying on the built-in and also add test cases with int8 and uint8 arrays.

Fix return types for some of the unary ops

---

cunumeric/module.py

Reimplemented `np.block` w/ slices to avoid creating intermediate arrays by concatenation. 
This PR includes changes in _concatenate, which removes verbose code.
Slicing-based block performs better for most cases on a single node. 
For multi-node, the communication from src to dest can be different depending on how intermediate arrays are partitioned. 
We keep the slicing-based block only and will come up with some ways to avoid perf degradations for some cases in a separate PR.

Slicing-based `np.block` implementation

---

cunumeric/array.py
cunumeric/module.py
src/cunumeric/unary/scalar_unary_red_template.inl
src/cunumeric/unary/unary_red_template.inl
tests/integration/test_view.py

This code is not compatible with functions that return views. For example, consider what happens when we fall back to NumPy arrays in this example:
```
x = cn.ones((1,))
y = x.reshape((1, 1))
y[:] = 2
```
The fallback code will execute the `reshape` operation onto a freshly allocated NumPy array mirroring `x`, and therefore `y` will not be a view over the same memory as `x`.
Instead of removing this path altogether we could just allow/block functions that cannot/might create views, but we had already been considering removing this path anyway, because it introduces blocking. @magnatelee do you have a preference on how to handle this?

Remove special case handling for scalar arrays

---

cunumeric/module.py
tests/integration/test_block.py

`np.append` failed when the input array is empty and `values` is not empty. 
This is because we excluded empty inputs in `_concatenate` in `_collect_outshape_slices`. 
So, we don't create slices for empty arrays while we do zipping of input arrays and slices, which results in mismatch of input arrays and slices. 
Added this case in `np.block` test which could fail for the same reason.

Fix the bug in `np.append` test on empty input array and non-empty scalars

---

cunumeric/array.py
cunumeric/coverage.py
tests/integration/test_array_dunders.py

I originally had higher hopes about this feature. I was hoping we could reuse some generic code in NumPy, like `np.multi_dot` and `np.matrix_power`, by convincing NumPy to just use our array objects without converting back to `np.ndarray`, which should fundamentally be possible, since we implement the same interface. See https://github.com/manopapad/cunumeric/commit/bd833be0a2d32a6ef40eda354e6f4b228e2db08a if you're curious on why I couldn't make this work.
Note that some of the code in `__array_ufunc__` would ideally go into a `coverage.py` wrapper, but I will need some advice on how to do that, as it will affect the coverage reporting (I would want to separate out each ufunc `foo` into multiple functions, like `foo.reduce` and `foo.accumulate`).

Implement __array_function__ and __array_ufunc__

---

cunumeric/array.py
cunumeric/runtime.py

We need to allow `find_or_create_array_thunk` to create `DeferredThunk`s for empty arrays as well. Consider this example:
```
x = cn.nonzero([0,0,0])[0]  # creates a deferred empty ndarray
y = cn.ones((0,))  # creates an eager empty ndarray
x + y
```
Here `DeferredThunk.binary_op` will try to convert all its arguments to `DeferredArray`s, and that will end up calling `find_or_create_array_thunk` on `y`.
This PR also fixes a typo discovered while fixing this.

Allow DeferredThunks to be created for empty arrays

---

cunumeric/_ufunc/ufunc.py
cunumeric/array.py
cunumeric/deferred.py
cunumeric/eager.py
cunumeric/module.py
cunumeric/thunk.py
src/cunumeric/arg.h
src/cunumeric/arg.inl
src/cunumeric/cuda_help.h
src/cunumeric/unary/scalar_unary_red.cc
src/cunumeric/unary/scalar_unary_red.cu
src/cunumeric/unary/scalar_unary_red.h
src/cunumeric/unary/scalar_unary_red_omp.cc
src/cunumeric/unary/scalar_unary_red_template.inl
src/cunumeric/unary/unary_red.cc
src/cunumeric/unary/unary_red.cu
src/cunumeric/unary/unary_red_omp.cc
src/cunumeric/unary/unary_red_template.inl
src/cunumeric/unary/unary_red_util.h
tests/integration/test_arg_reduce.py
tests/integration/test_logical.py
tests/integration/test_nonzero.py
tests/integration/test_reduction_axis.py

This PR to fix #359 and also make `count_nonzero` use the same template so that it can support `axis`.

Fix unary reductions

---

cunumeric/runtime.py

There are currently no tests that cover this. I will put this under test when I figure out a more general strategy for testing runtime arg configuration in client libraries.

Fix nargs for report:dump-csv

---

cunumeric/coverage.py

Simple fix to use more general type Mapping in place of Dict

Generalize Dict to Mapping for newer versions of mypy

---

examples/sort.py

1. Add option to specify using legate, cupy or numpy
2. Add option to specify which memory pool to use for cupy
3. Define time methods for cupy

Add support for using cupy in sort.py

---

cunumeric/array.py
cunumeric/linalg/linalg.py
cunumeric/sort.py

issues: fixes #412 
@magnatelee I think this is smaller in scope than you have imagined, but I am not sure much more is advised. Some notes:
* `array.py`, `sort.py`, `linalg.py`
I have applied the Numpy normalization functions in places where it seemed to make sense. Most locations were just passing values other functions. 
* `fft.py`
Most locations just do `computed_axis = (axis,) if axis is not None else None` which does not seem worth defining a new function for. One place calls a `_sanitize_user_axes` but that function does unique conversion that takes shape into account. 
* `deferred.py`
A few uses here, but handles comepletely differently, e.g. via `result.project`
* `ufunc.py`, `eager.py`
The few uses here just pass on to other functions
* `thunk.py`
no code, just signatures

Use Numpy axis normalizations where possible

---

cunumeric/array.py
cunumeric/module.py
tests/integration/test_fallback.py

One side effect of #353 is that it redirects all NumPy calls to cuNumeric whenever cuNumeric has an implementation. This is problematic because this happens unconditionally and the cuNumeric implementation is often incomplete; even if the user explicitly makes a NumPy call via the `numpy` module, it can still go to cuNumeric and crashes. This PR to remedy the situation by catching `NotImplementedError`s coming out from cuNumeric and falling back to NumPy.

Fall back to NumPy in __array_function__ and __array_ufunc__

---

examples/cholesky.py

All other examples report `Elapsed Time`. This will make existing parsing scripts usable with cholesky too.

Report Elapsed Time in cholesky's output

---

cunumeric/_ufunc/ufunc.py
tests/integration/test_floating.py

Because this test is not calling `sys.exit`, the test failures are not correctly registered. In this PR we fix the test and the failing test cases.

Fix test_floating.py test to call sys.exit

---

tests/_utils/args.py
tests/_utils/test_stages/test_stage.py
tests/_utils/tests/test_args.py
tests/_utils/tests/test_config.py

Requested by @fduguet-nv This PR adds support for a `-vv` option to `test.py`. When `-vv` is sprecified, the pytest `-s` option is added to the individual test file invocations that the `test.py` test runner launches. This will cause the `stdout` output, which is normally suppressed on passing tests, to be displayed unconditionally. 
It is recommended that this option be used in conjunction with the `--files` argument, in order to obtain more manageable output. Here is an example of such usage:
```
dev38 ❯ ./test.py --use=cuda,cpus,eager -vv --files tests/integration/test_binary_op_broadcast.py                         
############################################################
############################################################ …
```

Support -vv for more verbose test output

---

cunumeric/coverage.py
cunumeric/deferred.py
cunumeric/eager.py
cunumeric/runtime.py
cunumeric/thunk.py
pyproject.toml

I was hoping to have one PR to finish up, but `array.py` and the thunk modules are proving to be quite thorny. Pushing this PR to add `runtime.py` for now at least.

Add typing to runtime.py

---

tests/integration/test_compress.py
tests/integration/test_take.py

Here were some more tests that were not calling `sys.exit`, meaning that if the tests were to fail, the result would only be *printed*, but would not cause a CI job to fail (as it should). cc @marcinz I will work on #434 soon to help enforce this requirement on our test modules. 
As long as I was updating these files, I also took the opportunity to bring them more in line with the other test files, that split tests into discrete, descriptively named test functions, and utilize `pytest.parametrize`, etc. cc @ipdemes can you review and confirm that my changes preserve the intent of the original tests?
cc @magnatelee I didn't happen to see the original PR for this go by. I will try to be more pro-active regarding scanning new PRs, but if there are any that involve new tests please don't …

Update compress/take tests for pytest

---

.pre-commit-config.yaml
scripts/hooks/enforce_pytest_main.py
tests/unit/cunumeric/_sphinxext/test__comparison_util.py

This PR adds a new pre-commit hook `enforce-pytest-main` that ensures that all test modules end with 
```
sys.exit(pytest.main(sys.argv))
```
I had tried to originally test for 
```
if __name__ == "__main__":
import sys
sys.exit(pytest.main(sys.argv))
``` 
but there are a few tests that have more complicated "main checks" so that they can also be run as standalone scripts.

Add a pre-commit check to enforce pytest main convention

---

tests/_utils/system.py

This PR makes a small change to the test runner to make `pynvml` required for stages that access GPU information. Previously, if `pynvml` was missing, and the GPU stage was run, `system.gpus` would return an empty list of GPU specs, resulting in a cryptic error suggesting that there were no GPUs present (even if there were):
```python
Traceback (most recent call last):
File "./test.py", line 30, in <module>
plan = TestPlan(config, system)
File "/home/idemeshko/development/cunumeric_clean/tests/_utils/test_plan.py", line 45, in __init__
self._stages = [
File "/home/idemeshko/development/cunumeric_clean/tests/_utils/test_plan.py", line 46, in <listcomp>
STAGES[feature](config, system) for feature in config.features
File "/home/idemeshko/development/cunumeric_clean/tests/_utils/test_stages/gp …
```

Make missing pynvml an error for GPU tests

---

cunumeric/array.py
cunumeric/coverage.py
tests/integration/test_array_fallback.py
tests/unit/cunumeric/test_coverage.py

This PR renames the `clone_class` decorator to `clone_np_ndarray` to reflect the fact that it is closely tied to the implementation of `np.ndarray`. 
Additionally, this PR fixes the issue reported by @fduguet-nv 
```
>>> import cunumeric as num
>>> ones = num.ones((10,))
>>> ones.mean()
array(1.)
>>> ones.std()
<console>:1: RuntimeWarning: cuNumeric has not implemented numpy.ndarray.std and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/home/fduguet/github/cunumeric-fduguet/cunumeric/coverage.py", line 165, in wrapper
return func(*args, **kwargs)
TypeError: descriptor 'std' for 'numpy.ndarray' objects doesn't apply to a 'ndarray' object
```
A fix …

Fallback to self = np.ndarray when necessary

---

cunumeric/_sphinxext/_comparison_config.py
scripts/api_compare.py

This PR has minor updates/fixes for `api_compare.py`:
* Numpy 1.23 removed deprecated `np.asscalar` entirely
* Sphinx ext support code moved to private module
With these changes the script is functional again:
```
gas38 ❯ legate scripts/api_compare.py 
group,numpy,cunumeric,cupy
Convolve and Correlate,2,1,2
Ufuncs,91,87,86
Logical operations,14,12,11
Einsum and related,6,6,6
Discrete Fourier transform,18,14,18
Set operations,7,1,3
Array manipulation,48,25,41
Array manipulation (ndarray),1,1,1
Factorizations,2,1,2
SVD and related,4,0,4
Eigenvalues,4,0,2
LU factorization and related,6,0,6
Input and output,20,0,17
Input and output (ndarray),2,2,2
Array creation,29,17,25
Array creation (ndarray),1,1,1
Mathematical functions,30,7,27
"Searching, sorting, and counting",18,12,18
Advanced …
```

Updates to api_compare.py

---

cunumeric/coverage.py
tests/unit/cunumeric/test_coverage.py

As noted in #462 it seems that the coverage machinery is a little over-eager. Specifically, it is applying `._cunumeric` metadata to "extra" things that exist in `cunumeric` but don't exist in `numpy`, e.g. `add_boilerplate` as one example. This is does not really cause any problems directly, i.e. the coverage reporting is not affected by it. But the superfluous metadata can make things annoying for other use-cases (e.g. needing to add a `SKIP` list in #462)

Be stricter applying CuWrapperMetadata

---

src/cunumeric/unary/unary_op_util.h
tests/integration/test_unary_ufunc.py

Floating point predicates were instantiating wrong variants for complex types. This PR fixes the issue, and also removes incorrect uses of `constexpr`.

Fix for floating point predicates

---

conda/environment-test-3.10.yml
conda/environment-test-3.8.yml
conda/environment-test-3.9.yml

I had to add upper version for `markdown` due to some breaking changes to it that are not yet supported  in the latest release of the `sphinx-markdown-tables`.
Please see more details here: https://github.com/ryanfox/sphinx-markdown-tables/issues/36

markdown version fix

---

cunumeric/_sphinxext/missing_refs.py
docs/cunumeric/source/conf.py

This is a first partial step towards #460 The simplest way to implement is to automatically generate an `_all.rst` file that simply lists references to all implemented functions, and then let Sphinx warn/error if any are missing. However, in #420 Sphinx's built-in "nitpicky" mode was disabled, because is was too annoyingly over-broad, so missing references no longer generate warnings/errors.
This PR adds a new `missing_refs` sphinx extension that warns about missing references, *but only for explicitly added `cunumeric.*` references*.
Some notes:
* Using the `_all.rst` (to be added in the next PR) the current list of "missing" refs is all dunders:
```
/home/bryan/work/cunumeric/docs/cunumeric/source/_all.rst:3: cunumeric.ndarray.__array_function__ …
```

Add custom nitpicky ref checks for cunumeric APIs

---

cunumeric/array.py
tests/integration/test_get_item.py
tests/integration/test_set_item.py

Another attempt at solving https://github.com/nv-legate/cunumeric/issues/472, using the `operator.index(.)` method instead of `int()`, as the python documentation suggests, and handling some additional cases (also support indexing numpy ndarrays and python lists).

Allow scalar cunumeric ndarrays as array indices

---

cunumeric/_sphinxext/implemented_index.py
cunumeric/_sphinxext/missing_refs.py
cunumeric/coverage.py
cunumeric/random/generator.py
cunumeric/random/random.py
docs/cunumeric/source/_implemented.rst
docs/cunumeric/source/api/random.rst
docs/cunumeric/source/conf.py
tests/unit/cunumeric/test_coverage.py

ref: closes #460 
This PR does the following:
* Fixes a bug with wrapping ufuncs where `@wraps` fails to correctly capture the object name
* Simplifies `MissingRefs` to report warnings individually (Sphinx will print all of them)
* Adds an `ImplementedIndex` that creates a reference for every "implemented" function that is not explicity skipped. 
This last is an implicit check that all implemented functions are present in the docs, since otherwise a missing-refs warning will be triggered. 
I have explicitly skipped the following missing items:
```
SKIP = (
"cunumeric.cast",
"cunumeric.ndarray.__array_function__",
"cunumeric.ndarray.__array_ufunc__",
"cunumeric.ndarray.__format__",
"cunumeric.ndarray.__hash__",
"cunumeric.ndarray.__iter__",
"cunumeric.ndarray.__radd__", …
```

Docs coverage check

---

cunumeric/array.py
cunumeric/runtime.py
tests/integration/test_array_creation.py

Sanitize shapes in `ndarray`'s constructor

---

cunumeric/_sphinxext/_comparison_config.py
cunumeric/module.py
docs/cunumeric/source/api/manipulation.rst
docs/cunumeric/source/api/math.rst
docs/cunumeric/source/api/ndarray.rst
tests/integration/test_ndim.py

`cunumeric.ndim`

---

src/cunumeric/convolution/convolve_omp.cc

These have been accidentally working for `FastDivmodU64` on tested platforms since `uint64_t` is the same as `size_t`. This fails on platforms where `uint64_t&` cannot bind a `size_t`.

fix mismatched size_t/uint64_t types

---

src/cunumeric/sort/sort_cpu.inl

Not all compilers support these, so just use thrust.

src/cunumeric/sort: stop using std::{inclusive, exclusive}_scan

---

conda/conda-build/build.sh
conda/conda-build/meta.yaml

Curand is provided as a separate package in the Nvidia conda packaging system. The Nvidia channel `cudart-dev` package relies on some include files from `cuda-nvcc`. This is probably a bug (reported), but for now we need `cuda-nvcc` for the files that are included from curand and then from cudart.

Add support for curand conda package build

---

conda/conda-build/build.sh
conda/conda-build/meta.yaml

Conda packages now build with support for curand both in the CPU and the GPU builds.
Co-authored-by: Marcin Zalewski <mzalewski@nvidia.com>

Add support for curand conda package build (cherry pick #510)

---

.github/workflows/ci.yml
test.py
tests/_utils/__init__.py
tests/_utils/args.py
tests/_utils/system.py
tests/_utils/test_plan.py
tests/_utils/test_stages/cpu.py
tests/_utils/test_stages/eager.py
tests/_utils/test_stages/gpu.py
tests/_utils/test_stages/omp.py
tests/_utils/test_stages/test_stage.py
tests/_utils/tests/test___init__.py
tests/_utils/tests/test_stages/test_cpu.py
tests/_utils/tests/test_stages/test_eager.py
tests/_utils/tests/test_stages/test_gpu.py
tests/_utils/tests/test_stages/test_omp.py
tests/_utils/tests/test_system.py
tests/_utils/tests/test_ui.py
tests/_utils/ui.py

Still WIP but I want to see how CI performs.

[WIP] Collate test output to allow workers > 1 with verbose output

---

tests/integration/test_unary_ufunc.py

Reciprocal is not valid for integers, which leads to test failures on certain platforms. 
https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html
* Splits math ufunc tests into default operations and operations needing special values
* Enables easier customization of input values to the different tests
* Simplifies syntax for calling tests since all tests only take a single argument
* Uses a hash-based seed for initializing random values so that tests use the same values whether tests are run individually or all-at-once

Fix reciprocal tests for zero values and improve test value customization

---

src/cunumeric/index/advanced_indexing.cu

* Fix for an off-by-one bug
* Shared memory size had not been passed to the kernel launch

Bug fixes for advanced indexing

---

cunumeric/deferred.py
tests/integration/test_append.py
tests/integration/test_array_creation.py
tests/integration/utils/utils.py

Enhance test_append and test_array_creation
1.  add negative tests
2.  add more test cases
3.  refactor test code

Enhance two integration tests

---

src/cunumeric/matrix/potrf.cc
src/cunumeric/matrix/potrf_omp.cc

This is working around some recent changes to OpenBLAS. Previously we were using
the internal names for functions, e.g. "spotrf_". OpenBLAS changed the
definitions of these internal functions, so in a previous PR we switched to
using the public functions, e.g. "LAPACK_spotrf". These used to be function
symbols, but in the latest update OpenBLAS changed these to be macros.

Handle the case where LAPACK_*potrf is a macro, not a function

---

src/cunumeric/matrix/potrf.cc
src/cunumeric/matrix/potrf_omp.cc

Cherry-pick #527 into branch 22.07.

Handle the case where LAPACK_*potrf is a macro, not a function (#527)

---

src/cunumeric/binary/binary_red.cu
src/cunumeric/cuda_help.h
src/cunumeric/device_scalar_reduction_buffer.h
src/cunumeric/index/advanced_indexing.cu
src/cunumeric/index/repeat.cu
src/cunumeric/matrix/dot.cu
src/cunumeric/search/nonzero.cu
src/cunumeric/unary/scalar_unary_red.cu

* Unify the template for device reduction tree and do some cleanup
* Fix performance bugs in scalar reduction kernels:
* Use unsigned 64-bit integers instead of signed integers wherever
possible; CUDA hasn't added an atomic intrinsic for the latter yet.
* Move reduction buffers from zero-copy memory to framebuffer. This
makes the slow atomic update code path in reduction operators
run much more efficiently.
* Use thew new scalar reduction buffer in binary reductions as well
* Use only the RHS type in the reduction buffer as we never call apply
* Minor clean up per review
* Rename the buffer class and method to make the intent explicit
* Flip the polarity of reduce's template parameter

Fix performance bugs in scalar reductions (#509)

---

src/cunumeric/stat/bincount.cu
src/cunumeric/stat/bincount_omp.cc

There are variants in the `bincount` implementation that are dead. This PR removes them.

Remove dead code in `bincount`

---

tests/integration/utils/random.py

The current validation check for random distributions is causing random test failures in the CI. It simply checks if the standard deviation of the samples is close enough to the theoretical value, but failing this test doesn't have any statistical significance unless we draw extremely many samples. (i.e., a particular run might be simply very unlucky.) until we find a better way to validate samples, this PR simply relaxes the check to avoid any unexpected and undesirable test failures.

Make the validation condition for random distributions lenient

---

cunumeric/deferred.py
tests/integration/test_slicing.py

With https://github.com/nv-legate/legate.core/pull/340 we can now inline map 0D stores, but the allocations are 1D instead of 0D, due to the limitation in Legion. This PR adds a reshaping call to turn them back to 0D.

Construct NumPy arrays correctly from 0D deferred arrays backed by region fields

---

tests/_utils/stages/__init__.py
tests/_utils/stages/test_stage.py
tests/_utils/stages/util.py
tests/_utils/system.py
tests/_utils/test_plan.py
tests/_utils/tests/stages/test_test_stage.py
tests/_utils/tests/test_system.py

This PR changes the test runner to collect and display details of all individual test failures in one place at the end of the run:
With this change it is not necessary to add `-v` just to see the details of test failures.

Collect test failure details at the end

---

src/cunumeric/unary/convert_util.h

Some compiler doesn't like a single if-else statement in a value-returning function that has a return statement in both branches.

Fix a compiler warning

---

tests/_utils/args.py
tests/_utils/config.py
tests/_utils/stages/_linux/cpu.py
tests/_utils/stages/_linux/omp.py
tests/_utils/tests/stages/_linux/test_cpu.py
tests/_utils/tests/stages/_linux/test_omp.py
tests/_utils/tests/test_args.py
tests/_utils/tests/test_config.py

This PR replace the test runner `--strict-pin` option with `--cpu=pin={auto, none, strict}` instead
* `REALM_SYNTHETIC_CORE_MAP` is unset
* no +1 for python processor
* `--cpu-bind` args are omitted
* `REALM_SYNTHETIC_CORE_MAP` is unset
* no +1 for python processor
* `--cpu-bind` args are included
* `REALM_SYNTHETIC_CORE_MAP` is ***not*** unset
*  +1 is added for python processor
* `--cpu-bind` args are included
cc @manopapad is "auto" the best choice? Nothing is automatically computed based on anything. Maybe "loose" or "lax" would be better.

Add option to disable CPU pinning in tests

---

src/Makefile

@fduguet-nv informed me that linking with curand is not necessary.

Do not link curand

---

src/cunumeric/index/advanced_indexing.cu
src/cunumeric/index/advanced_indexing_omp.cc
src/cunumeric/omp_help.h

There are 2 issues fixed in this PR:
1) Fix CUDA kernel logic
2) Fix incorrect use of ThreadLocalStorage in the OpenMP kernel

Fixing issues with advanced_indexing_kernel

---

tests/_utils/stages/_osx/cpu.py
tests/_utils/stages/_osx/eager.py
tests/_utils/stages/_osx/omp.py
tests/_utils/system.py

This PR fixes two issues with the test runner on OSX:
* Inexplicably, there is a `pynvml` package that exists and can be imported on OSX (it just fails on initialization). The condition is handled more gracefully
* The CPU pinning PR made the OSX stages return empty shards since pinning is not possible on OSX. But at least need to return a dummy shard of the proper length for the stage to queue over.

Fix OSX test shard generation

---

.github/workflows/require-labels.yml

Exactly one of the `category` labels is required. Categories are:
- a bug fix (`category:bug-fix`)
- an improvement (`category:improvement`)
- a new feature (`category:new-feature`)
- a task (`category:task`)
The labels will be used to automatically generate release notes. A task is the only label that will cause a PR not to appear in the release notes.

Require labels on pull requests

---

tests/integration/test_unary_ufunc.py

The recent changes to the tests broke error printing when errors occur due to a change in `in_np`. This fixes the error printing.

fix error print in test_unary_ufunc

---

src/cunumeric/search/nonzero_omp.cc
src/cunumeric/set/unique_omp.cc

This commit fixes a bug where nonzero would always allocate data in
system memory for output buffers even when numa memories were available.
This led to error messages like:
```
[0 - 7f2e7001d000]    1.243573 {5}{runtime}: [error 608] LEGION ERROR: Field 1048586 of output region 0 of task cunumeric::NonzeroTask (UID: 58) is requested to have an instance on memory 1e00000000000002, but the returned instance is allocated on memory 1e00000000000000. (from file /opt/legate/legate.core/legion/runtime/legion/runtime.cc:5797)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_608
```

src/cunumeric/search: make nonzero not always allocate SYS_MEM buffers

---

cunumeric/deferred.py
tests/integration/test_advanced_indexing.py
tests/integration/test_get_item.py

This PR fixes https://github.com/nv-legate/legate.core/issues/329 and https://github.com/nv-legate/cunumeric/issues/515

Fixing logic for slicing 

---

cunumeric/module.py

Sanitize `k` for the `eye` operator

---

src/cunumeric/matrix/solve_template.inl
tests/integration/test_solve.py

This and [a companion PR](https://github.com/nv-legate/legate.core/pull/365) should address #583.

Fix `linalg.solve` when inputs are scalars

---

conda/conda-build/meta.yaml

It seems that the curand dependency is include only, so we can remove the run dependency.

Remove run dependency on curand

---

.github/workflows/require-labels.yml

When a PR is created, the authors will often set the labels soon after creation. We will have a "grace period" on a new pull request to allow setting labels after the PR is created.

Delay label checking on fresh PRs

---

cunumeric/deferred.py

We cannot create tight region requirements, that include just the diagonal we are writing, so necessarily there will be elements in the regions we pass to the eye call whose values must remain. Write-discard privilege, then, is not appropriate for this call, as it essentially tells the runtime that it can throw away the previous contents of the entire region.
Fixes #613

Invoke eye with read-write privilege, not write-discard

---

tests/integration/test_append.py
tests/integration/test_array_split.py
tests/integration/test_block.py
tests/integration/test_diag_indices.py
tests/integration/test_eye.py
tests/integration/test_flatten.py
tests/integration/utils/utils.py

Enhance test_diag_indices.py and test_flatten.py.

Enhance test_diag_indices.py and test_flatten.py.

---

examples/cg.py
examples/einsum.py
examples/jacobi.py
examples/logreg.py
examples/sort.py
examples/stencil.py

When running cupy tests, it raises RuntimeError.
Add RuntimeError exception to legate.time to fix it.

Add RuntimeError exception to legate.time

---

src/cunumeric/arg.cc
src/cunumeric/cunumeric.cu
src/cunumeric/unary/unary_red_util.h

It turns out that min and max reductions on complex types are rejected in the Python code even though the C++ reduction code was instantiating the template for those cases. This PR fixes the inconsistency by removing those instances.

Stop instantiating min and max reduction ops for complex types

---

cunumeric/_ufunc/ufunc.py
cunumeric/array.py
cunumeric/deferred.py
cunumeric/eager.py
cunumeric/thunk.py

This PR uses a feature added by https://github.com/nv-legate/legate.core/pull/364 to recycle storages for stores temporarily created by type conversions.

Mark temporary conversion outputs as linear for eager storage recycling

---

tests/integration/test_fill.py

`test_fill_int_with_none` was using a Python version-specific error string and failing on Python 3.10. This PR makes it more robust.

Make the negative test on `fill` robust across Python versions

---

src/cunumeric/matrix/solve_template.inl

This file was included unnecessarily, and led to build issues on distributed machines. In particular, including coll.h pulls in mpi.h, which is an unresolved header to NVCC.

src/cunumeric/matrix: stop including coll.h in solve_template.inl

---

src/cunumeric/matrix/solve_template.inl

This file was included unnecessarily, and led to build issues on distributed machines. In particular, including coll.h pulls in mpi.h, which is an unresolved header to NVCC.
Signed-off-by: Rohan Yadav <rohany@alumni.cmu.edu>

src/cunumeric/matrix: stop including coll.h in solve_template.inl (#620)

---

tests/integration/test_unary_ufunc.py

Certain tests can occasionally get negative values from randn, but they should only operate on positive values. This adds a floor value to the random number generators to ensure values are always positive.

Force positive values for log and sqrt tests

---

conda/conda-build/meta.yaml

The meta.yaml has a ignore_run_exports to ignore run_exports from legate-core, but this strips legate-core from the run requirements of cunumeric.
This patch adds legate-core back as a directly listed run requirement

Fix missing legate-core run requirement

---

.github/workflows/ci.yml

v2 -> v3 to avoid GitHub warnings.

Update upload artifact action version

---

src/cunumeric/set/unique.cu
tests/integration/test_unique.py

Fixes a bug in `cunumeric.unique` that launches an empty kernel.

Eliminate empty kernel launch in `cunumeric.unique`

---

install.py
scripts/build-install.sh
scripts/build-no-install.sh
scripts/build-separately-no-install.sh
scripts/build-with-legate-no-install.sh
scripts/build-with-legate-separately-no-install.sh
scripts/util/uninstall-global-legion-legate-core-and-cunumeric.sh

Addresses same problem as https://github.com/nv-legate/legate.core/pull/455, but in cuNumeric.

Make `install.py` reconfigure editable installs when build type changes

---

test.py

The PR moves the configuration of cunumeric-specific `SKIPPED_EXAMPLES` and `PER_FILE_ARGS` to cunumeric's `test.py` (where they belong). After this is merged, a corresponding PR in `legate.core` will change the default values in `legate.tester` to be empty. 
This is being done as part of adding support for additional overrides/customizations

Configure test overrides in the project test.py

---

docs/cunumeric/source/api/_ndarray.rst
docs/cunumeric/source/api/ndarray.rst

This PR adds the `ndarray.put` method to the docs, which was causing the docs build to fail.

Add missing put method to docs

---

.github/workflows/ci.yml

This PR adds a CI job to build the documentation, so that a PR will fail if the docs are not build-able. Currently the build docs are not saved off anywhere, but this could be potentially done.

Add CI job to build docs

---

conda/conda-build/build.sh

It is hard to determine how much of a conda build is the conda overhead, and how much is the actual build time. These printouts make it possible to check that.

Print build start and end times in a conda build

---

tests/integration/test_array_dunders.py
tests/integration/test_diag_indices.py
tests/integration/test_einsum.py
tests/integration/test_einsum_path.py
tests/integration/test_indices.py
tests/integration/test_ingest.py
tests/integration/test_lstm_simple_forward.py
tests/integration/test_matrix_power.py
tests/integration/test_min_on_gpu.py
tests/integration/test_moveaxis.py
tests/integration/test_multi_dot.py
tests/integration/test_norm.py
tests/integration/test_outer.py
tests/integration/test_random_creation.py
tests/integration/test_reduction_axis.py
tests/integration/test_vdot.py
tests/integration/test_window.py
tests/integration/utils/contractions.py

Currently tests import `cunumeric` in a wide variety of ways:
```
import cunumeric as cn
import cunumeric as lg
import cunumeric as np
import cunumeric as num
```
This PR standardizes all the tests to use the latter, since it is already the most prevalent. [1] Having consistent imports for `cunumeric` means that copy-pasted code (which IME happens often in test code) is on better footing, and also just affords a consistent expectation when reading the code.
I will try to note any divergence from this in any future test file PRs.
I've also updated "np" vs "num" test values to generally be "name first", i.e. `arr_num` and `arr_np` instead of `num_arr` and `np_arr` but only in files already changed in this PR (I'd regard this as ongoing code-gardening, not worth a big update in and of …

Minor test QOL improvements: make cunumeric  imports consistent

---

CMakeLists.txt
cmake/generate_install_info_py.cmake
cunumeric_python.cmake
scripts/build-install.sh
scripts/build-no-install.sh
scripts/build-separately-no-install.sh
scripts/build-with-legate-no-install.sh
scripts/build-with-legate-separately-no-install.sh

This PR adds a custom target to generate `install_info.py` on every build, not just the initial configure.
```shell
$ ninja -C cunumeric/_skbuild/linux-x86_64-3.9/cmake-build/
ninja: Entering directory `cunumeric/_skbuild/linux-x86_64-3.9/cmake-build/'
[2/2] Generate install_info.py
```

Regenerate `install_info.py` on every build

---

src/cunumeric/set/unique.cu

It looks like the code adds `lo` twice.
I was not able to actually exercise this code to verify the issue, because some part of the stack, likely the core's handling of output regions, always seemed to squash any non-compact arrays I produced (and ran the task on 1 GPU), in which case the copy kernel is skipped altogether:
```
print(cn.unique(cn.ones((20,)))) # naturally dense, code runs on all GPUs
print(cn.unique(cn.ones((20,))[3:])) # naturally dense, code runs on all GPUs
print(cn.unique(cn.ones((4,5))[1,:])) # naturally dense, code runs on all GPUs
print(cn.unique(cn.ones((4,5))[:,2])) # someone densifies the input, code runs on 1 GPU only
print(cn.unique(cn.ones((4,5))[1:3,2:4])) # someone densifies the input, code runs on 1 GPU only
```

Fix a typo in unique.cu indexing

---

cunumeric/__init__.py
cunumeric/array.py
cunumeric/coverage.py
cunumeric/deferred.py
cunumeric/eager.py
cunumeric/linalg/linalg.py
cunumeric/module.py
cunumeric/runtime.py
cunumeric/sort.py
cunumeric/utils.py
pyproject.toml

This PR makes some minor type improvements across the code base:
* all `type: ignore` made fully specific (with one exception, see below)
* type ignores for optional values removed w/ assertions
* an obsolete `mypy` config value was removed
I left the generic `type: ignore` in `deferred.py` for all the `.base` cases. I think there is a larger issue to resolve here where some things claim to want `Union[DeferredArray, NumpyThink]` but then access `.base` which only exists on the `DeferredArray`
Somewhat related, I think the largest issue remaining is all the `Any` for thunk/array args (e.g. `rhs`, etc). This will requrie some thought and possibly some re-org. It should get a dedicated PR.

Minor type improvements

---

cunumeric/array.py
cunumeric/logic.py
cunumeric/random/random.py

Inspired by https://github.com/nv-legate/cunumeric/issues/464, I took a look at some "contentious" Availability annotations. I updated some to follow this policy, that I suggest going forward:
A function implementation gets full marks ("Multiple CPUs, Multiple GPUs") if it does not impede multi-CPU and multi-GPU execution, more than the function's semantics require.
Examples:
* `cn.add`: has data-parallel CPU and GPU implementations => full marks
* `cn.iscomplexobj`: only checks the `dtype` of the array object, therefore it doesn't impede distributed execution => full marks (doesn't matter that it falls back to `np.iscomplexobj` in the case of vanilla NumPy arrays, since that array is already local, and thus doing so doesn't impede distributed execution; doesn't matter that it doesn't …

Update Availability annotations

---

src/cunumeric/sort/sort.cu

Adding guards to prevent zero sized sends/receives during NCCL all2all block. This helped to circumvent the issue observed in #722 .

guard all2all from empty transfer

---

src/cunumeric/item/read.h
src/cunumeric/item/write.h

This commit adds OMP variants for the write and read tasks so that they can be used in resource-scoped settings where openmp processors are desired.
Signed-off-by: Rohan Yadav <rohany@alumni.cmu.edu>

src/cunumeric/item: add openmp variants for write/read tasks

---

cunumeric/eager.py
tests/integration/test_ndim.py

@bryevdv Previously NumPy would accept this input, but as of 1.24 it doesn't:
```
np.ndim( ([0], [1, 2], [3, 4, 5]) )
```
So I don't know how to mark the test that compares NumPy and cuNumeric behavior on this input. On NumPy 1.23 it would be a test that's expected to pass, whereas on 1.24 it would be an xfail, since NumPy will exit with a failure. So I just removed that test for now.

Fix CI failures due to numpy 1.24 upgrade

---

examples/benchmark.py
examples/black_scholes.py
examples/cg.py
examples/einsum.py
examples/gemm.py
examples/indexing_routines.py
examples/jacobi.py
examples/kmeans.py
examples/kmeans_slow.py
examples/kmeans_sort.py
examples/linreg.py
examples/logreg.py
examples/lstm_backward.py
examples/lstm_forward.py
examples/lstm_full.py
examples/richardson_lucy.py
examples/scan.py
examples/solve.py
examples/sort.py
examples/stencil.py

CuPy launches work asynchronously on the GPU, so we need to block until all work finishes before taking a measurement.

Fix timing for CuPy tests

---

install.py

This PR ensures scikit-build uses the desired generator for all CMake invocations. This short-circuits scikit-build's internal generator "detection" logic, which caused failures if they detected a different generator than the one we were specifying.

Pass `CMAKE_GENERATOR` to scikit-build

---

install.py

Change the default architecture to haswell. Currently, we build our conda packages with haswell to avoid compatibility issues. Changing the default architecture to haswell will make default builds comparable to the conda packages and it will allow developers to share sccache with CI builds.

Change the default CPU architecture to haswell

---

cunumeric/coverage.py
cunumeric/random/__init__.py

fixes #761 
Some functions in `numpy.random` were being missed by `clone_module` because their type is `BuiltinFunctionType` which was not previously included by the `coverage` machinery. Presumably the functions have this type because they are implemented in C. Unfortunately, we cannot just add this new type unconditionally everywhere, since it will pick up actual built-in functions, which causes problems. As a compromise, the addition of this type was put behind a flag, which is now turned on only when `numpy.random` is cloned. 
With this change:
```
dev310 ❯ legate ~/tmp/foo.py 
/home/bryan/tmp/foo.py:2: RuntimeWarning: cuNumeric has not implemented numpy.random.permutation and is falling back to canonical numpy. You may notice significantly decreased performance for this function …
```

handle numpy 'builtins' properly for coverage

---

conda/conda-build/meta.yaml

The latest version of curand requires newer cuda. We switched CI to cuda 11.8, so we can use the latest curand package.

Unrestrict curand version

---

cunumeric/__init__.py
cunumeric/args.py
cunumeric/runtime.py

This PR has prefactory work to allow the legate driver help to include command-line flags for known, installed downstream projects e.g. cunumeric.
In order to allow `cunumeric.ARGS` to importable form plain-python apps like the driver, an environment variable "override" can be set to suppress all the API imports. This is clunky, but is only utilized in the driver's `print_help` function

Expose command args for legate driver help. 

---

tests/integration/test_append.py
tests/integration/test_array_creation.py
tests/integration/test_flatten.py
tests/integration/test_moveaxis.py
tests/integration/test_put_along_axis.py
tests/integration/test_take_along_axis.py

Happened to notice that some of our tests use a deprecated form of defining a setup method:
```
tests/integration/test_put_along_axis.py::TestPutAlongAxisErrors::test_values_bad_shape[(shape=(1, 0))]
/home/bryan/anaconda3/envs/dev310/lib/python3.10/site-packages/_pytest/fixtures.py:900: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
tests/integration/test_put_along_axis.py::TestPutAlongAxisErrors::test_values_bad_shape[(shape=(1, 0))] is using nose-specific method: `setup(self)`
To remove this warning, rename it to `setup_method(self)`
```
This PR performs the rename wherever appropriate in order to avoid surprise failures with a future version of `pytest`

Rename setup to setup_method

---

conda/conda-build/build.sh

Because the build of dependencies is configured during the configure stage of cmake, we need to set parallelism during that stage as well.

Forward parallelism level to dependencies when building with cmake in conda

---

cunumeric/module.py
tests/integration/test_linspace.py

Did some quick runs to ascertain the casting behavior:
```
>>> for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64, np.float16, np.float32, np.float64, np.complex64, np.complex128]:
...     print(dtype, np.linspace(dtype(0),dtype(100),3).dtype)
...
<class 'numpy.int8'> float64
<class 'numpy.int16'> float64
<class 'numpy.int32'> float64
<class 'numpy.int64'> float64
<class 'numpy.uint8'> float64
<class 'numpy.uint16'> float64
<class 'numpy.uint32'> float64
<class 'numpy.uint64'> float64
<class 'numpy.float16'> float64
<class 'numpy.float32'> float64
<class 'numpy.float64'> float64
<class 'numpy.complex64'> complex128
<class 'numpy.complex128'> complex128
>>> np.linspace(np.int32(0),np.float32(100),3).dtype
dtype('float64')
>>> …
```

Avoid an internal use of np.result_type

---

docs/cunumeric/source/conf.py

Recently released pydata-sphinx theme 0.13 has some issues:
* deprecation warning causes build fail with strict warnings enabled
* https://github.com/pydata/pydata-sphinx-theme/issues/1220 
We could also cap the theme version to 0.12 but as long as we have to update three repos to set a version I'd rather set 0.13 as new min. 
@magnatelee I did verify that legate docs PR builds with 0.13

Changes for sphinx theme 0.13

---

tests/integration/test_unary_ufunc.py

Otherwise multi-node testing will fail, because different ranks will get different inputs.
`hash()` is deterministic within a run/process, but not across runs/processes.

Ensure unary_func seeding is deterministic across processes

---

cunumeric/deferred.py
cunumeric/linalg/cholesky.py
cunumeric/runtime.py
cunumeric/sort.py

This PR updates the `cunumeric ` codebase to only use the explicit (and more narrowly typed) `create_auto_task` and `create_manual_task`.
A separate PR to `legate.core` will remove the combined `create_task` entirely.

Use explicit task creation APIs

---

CMakeLists.txt

Switch to rapids-cmake 23.04 early

---

cunumeric/module.py
tests/integration/test_array_creation.py

Implements the first part of https://github.com/nv-legate/cunumeric/issues/840.

Support of the `shape` argument in `empty_like()` & Co.

---

cunumeric/module.py
tests/integration/test_concatenate_stack.py

Change list:
1. In check_shape_dtype, and should be replaced by or.
2. In check_shape_dtype, check shapes of all input arrays for stack. This is necessary for stack.
3. In check_shape_dtype, if ndim==1, set axis to be 0 for hstack. The default axis value from def hstack in module.py is 1.
4. In check_shape_dtype, change ndim > 1 to ndim >= 1. This is necessary for checking 1-D array size for column_stack.
5. In check_shape_dtype, change shape[1:axis] to shape[:axis]. I think the first size of shape should also be checked. Or is it omitted purposefully?
6. In check_shape_dtype, normalize axis if axis < 0 and axis >= -ndim. Otherwise, axis=-1 would cause bugs in shape[axis+1:] for append API. We don't use normalize_axis_index here because it raises error for the column_stack case where …

Fix bugs in concatenate and stack APIs.

---

conda/conda-build/conda_build_config.yaml
conda/conda-build/meta.yaml

This includes three changes for the conda build scripts:
1) Updates how the restriction on python 3.9.7 is done through run_constrains
2) Adds py311 to the build matrix
3) Updates to 11.8 since SM90 is included in the build command

Update Conda build scripts

---

CONTRIBUTING.md
docs/cunumeric/Makefile

This PR adds a new `linkcheck` target to the Makefile, to run the built-in Sphinx [`CheckExternalLinksBuilder`](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) by invoking `sphinx-build -b linkcheck`.  This feature has several [configurable options](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder) however the defaults all seem approprtiate. This check will cover all external links, including intersphinx links to numpy, etc. Presumably we trust Sphinx not generate bad internal links. 
cc @manopapad for some questions:
* This PR also removes the `legate` invocation for `sphinx-build` in the Makefile. Since the "standard Python" work, this is no longer necessary
* The existing …

Add a linkcheck target to docs build

---

conda/conda-build/build.sh

Thanks to @syamajala for discovering that our CPU-only packages contain AVX-512 instructions:
```
> wget https://anaconda.org/legate/cunumeric/23.03.00/download/linux-64/cunumeric-23.03.00-cuda11_py39_g9ac887b8_50_cpu.tar.bz2
> tar -xjvf cunumeric-23.03.00-cuda11_py39_g9ac887b8_50_cpu.tar.bz2
> objdump -d lib/libcunumeric.so  | grep vcvtusi2sd
25b96b:	62 d1 67 08 7b d7    	vcvtusi2sd %r15d,%xmm3,%xmm2
25b996:	62 f1 67 08 7b c8    	vcvtusi2sd %eax,%xmm3,%xmm1
```

Also build CPU-only packages for haswell

---

cunumeric/module.py
tests/integration/test_concatenate_stack.py

1. In module.py, reshape inputs to at least 1-D array for concatenate(axis=None), hstack and column_stack
2. In module.py, in stack, set ndim to 0 for scalar inputs
3. In module.py, call ```normalize_axis_index``` for scalar inputs
4. In test code, add scalar tests for each API
5. In test code, remove xfails

Fix concatenate and *stack APIs to support scalars(#818, #839)

---

.github/workflows/ci.yml
cmake/versions.json
cunumeric_cpp.cmake

Currently, the cunumeric CI relies on the legate.core artifacts. However, recently, the version of legate.core has been explicitly hardcoded into cunumeric. To account for this, we will stop using legate.core generated packages, and instead we will build legate.core using the cunumeric build system.

Separate cunumeric CI from legate.core CI

---

CMakeLists.txt
cmake/thirdparty/get_tblis.cmake

Certain vendors (e.g. Apple, HPE Cray) have the bad habit of providing a single compiler entrypoint (`clang` in the case of Apple's XCode), and a bunch of symlinks to that one entrypoint for the various languages (e.g. `cc` and `c++` both link to `clang`). That is fine, however inside the shared entrypoint the code is taking cases depending on which symlink was used to invoke it. In the case of XCode, invoking `clang` through `cxx` will activate C++-mode, whereas invoking it through `cc` (or simply using the shared entrypoint directly) will activate C-mode, which will not link against the standard C++ library:
```
~/Desktop> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ must-be-compiled-with-cpp.cc
~/Desktop> …
```

Avoid following compiler symlinks

---

src/cunumeric/binary/binary_op_util.h

Some binary operators on `float16` that go through `float32` to compute the results don't actually compile, and this PR fixes it. The issue is currently masked by an incorrect type trait `legate::is_floating_point` returning `false` for `LegateTypeCode::HALF_LT` (which will be fixed in a follow-on PR).

Fix for some binary operators on float16

---

cmake/thirdparty/get_tblis.cmake

It looks like the previous symlink-following behavior that https://github.com/nv-legate/cunumeric/pull/880 changed was necessary on some systems, because on those systems `/usr/bin/cc` was a symlink to `/usr/bin/gcc`, and TBLIS is using the output from `--version` to discover the compiler vendor, and for gcc the actual compiler name reported on the `--version` output is not the literal string "gcc", but rather the name of the program used to launch the compiler (i.e. `argv[0]`). I submitted https://github.com/devinamatthews/tblis/pull/56 to work around this issue. Switching to using the PR branch on my personal fork of TBLIS, until that PR gets merged upstream.

WAR for TBLIS compiler detection while upstream PR is pending

---

cunumeric/module.py
tests/integration/test_bincount.py

For the three tests that are shown as removed, they're just moved into `TestBincountNegative`.

Improve code coverage for cunumeric.bincount

---

tests/unit/cunumeric/test_settings.py

This PR introduces a workaround for #907 by skipping the tests. A more long term solution should be researched and implemented as a fix for #907.

Skip codebase checks in CI

---

cunumeric/module.py
tests/integration/test_array.py

Root cause:
old code: `shape = (np.newaxis,) * (ndmin - result.ndim) + result.shape`
As np.newaxis is recognized as None, it would result in invalid shape, e.g. (None, None, 2，2).
Fix:
new code: `shape = (1,) * (ndmin - result.ndim) + result.shape`

Fix array API(#885).

---

.github/ops-bot.yaml

Setting up config files to for the rapids ops bot so we can leverage their CI resources in the short-term.
This change only enables the PR copying behavior so that we can submit CI requests from the context of the repo itself. It does **not** enable any workflows against the CI machines yet. Branches are automatically deleted when the associated PR is closed.

Add ops-bot config file

---

cmake/thirdparty/get_tblis.cmake

The upstream PR has now been merged.

Revert "WAR for TBLIS compiler detection while upstream PR is pending (#890)"

---

tests/integration/test_extract.py
tests/integration/test_prod.py

- Improve `prod` coverage to 100%
- Rearrange some of the tests into the correct test class and changed the naming.
- `test_dtype_negative` --> `test_dtype_integer_precision`, this is not a negative test.
- `test_dtype_complex_negative` is removed, parameters are merged into `test_dtype_complex`
- `test_axis_tuple` --> moved into positive tests
- Add more comments to some of the xfail tests to indicate the repro condition
- These failures are mentioned in https://github.com/nv-legate/cunumeric/issues/736, but they're not reproducible if `LEGATE_TEST=1` or `CUNUMERIC_TEST=1` is not set.
- Compare exceptions in negative tests.
- Fix the coverage for `cunumeric.place`, some of the lines slipped through after the last change in https://github.com/nv-legate/cunumeric/pull/892

Improve cunumeric.prod coverage and some test fixes

---

cunumeric/linalg/cholesky.py
cunumeric/runtime.py
cunumeric/settings.py
tests/unit/cunumeric/test_settings.py

This PR removes usages of  `CUNUMERIC_TEST` in favor of single `LEGATE_TEST`. There is a corresponding `legate.core` PR to stop setting `CUNUMERIC_TEST` in the tester codepaths: https://github.com/nv-legate/legate.core/pull/715

Unify LEGATE_TEST and CUNUMERIC_TEST

---

.github/workflows/ci.yml

The line setting `PYTHONFAULTHANDLER` was incorrect.

Fix python fault handler variable in CI workflow

---

tests/integration/test_array.py
tests/integration/test_trilu.py
tests/integration/test_trilu_indices.py

- Improve code coverage
- Change built-in name `object` to `obj`

Improve code coverage for array and trilu

---

examples/black_scholes_greeks.py

[This new Black-Scholes example](https://github.com/nv-legate/cunumeric/blob/branch-23.07/examples/black_scholes_greeks.py) takes fairly long in its default configuration, which makes local testing really painful. This PR adjusts the default configuration so it finishes at least in a minute on 4 CPUs even in debug mode. (takes ~44s on my machine.)

Adjust the iteration count for Black-Scholes example

---

conda/conda-build/meta.yaml

nccl no longer explicitly requires cudatoolkit, so we can remove it from our dependencies.

Remove cudatoolkit from conda metadata

---

cunumeric/random/random.py

Extends the fix for https://github.com/nv-legate/cunumeric/issues/798 to also cover `np.random.RandomState`. This should allow code like the following to not take forever:
```
indices = cn.arange(100000)
generator = cn.random.RandomState(42)
generator.shuffle(indices)
```
CC @betatim

Fall back to NumPy eagerly on RandomState methods

---

cunumeric/_ufunc/ufunc.py
cunumeric/array.py
cunumeric/linalg/linalg.py
cunumeric/module.py
tests/integration/test_binary_op_typing.py

This is an abridged version of #972 to clear up CI issues, that updates everything except a few more complicated uses of `find_common_types`.
A `test_argsort.py` test is failing for me locally, but also fails for me locally on `branch-23.07` so I don't think it is related.

Resolve numpy 1.25 issues

---

CMakeLists.txt
cunumeric_cpp.cmake
cunumeric_python.cmake

Works around https://github.com/nv-legate/cunumeric/issues/835 until https://github.com/rapidsai/rapids-cmake/issues/426 is addressed.
Also take this opportunity to bump rapids-cmake version.

Set lib_dir explicitly to lib/, even on RHEL

---

cunumeric/array.py
tests/integration/test_input_output.py

These are mostly np wrappers so more of a "in case we change something in the future", plus a minor bug fix to get tofile working. https://github.com/nv-legate/cunumeric/issues/969

Add tests for the input output related apis

---

cunumeric/_sphinxext/_comparison_config.py

This PR fixes docs breakage due to the introduction of `_ArrayFunctionDispatcher` in numpy 1.25 for functions in `np.linalg` . Specifically, the API comparison generation failed due to no longer being able to automatically collect any `np.linalg` functions. 
@manopapad I don't love this solution, but I am not sure what would be better. Not only is `_ArrayFunctionDispatcher` nominally private, but trying to access it normally raises an error:
```python
In [4]: type(np.linalg.cholesky)
Out[4]: numpy._ArrayFunctionDispatcher
In [5]: np._ArrayFunctionDispatcher
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 np.__ArrayFunctionDispatcher
File …
```

Fix docs breakage from np 1.25

---

cunumeric/array.py
tests/integration/test_array_dunders.py

To allow potential wrapping e.g. via projects like pint, cuNumeric should only accept types in the `__array_function__` and `__array_ufunc__` protocols that it clearly understands. Right now, these are superclasses (if there was subclassing in theory) and NumPy arrays.  CuPy arrays would also fall into this category.
Ping @manopapad since we talked about it briefly yesterday, thought I would just look into it.  It is correct that cuNumeric currently only knows about NumPy arrays really (and objects that don't have `__array_function__`/`__array_ufunc__`); i.e. no cupy?
I would lean towards it being OK to just fail if you don't implement this.  Dask has a [FutureWarning](https://github.com/dask/dask/blob/85c99bc20abc382774cfb6e5bf5f2db76ac09378/dask/array/core.py#L1718C24-L1718C24) for …

Ensure ufunc/function dispatching is narrow

---

cmake/versions.json

bump core to bring in [this](https://github.com/nv-legate/legate.core/commit/ac75ac05a9056f49729797415ee489b45686a528) change

Bump legate core to pin host compilers to 11.*

---

src/cunumeric/arg.inl

This fix was added in 9de32a010e8ac2a04850ae30484fb69148bdadc0, but got dropped in #903.

Fix Wundefined-var-template clang warning

---

CMakeLists.txt
cmake/versions.json

Change version of cunumeric to `23.09.00` and change the version of legate.core to `23.09.00` (bump up the git tag accordingly).

Bump up cunumeric version and legate.core version

---

cunumeric_cpp.cmake
src/cunumeric/mapper.cc
src/cunumeric/random/bitgenerator.h
src/cunumeric/set/unique_reduce.cc
src/cunumeric/set/unique_reduce.h
src/cunumeric/set/unique_reduce_omp.cc
src/cunumeric/set/unique_reduce_template.inl

This commit allows codes that use resource scoping and OpenMP processors to avoid crashes when using the corresponding numpy functions (random, unique) within a scope of only openmp processors.

src/cunumeric: add missing openmp variants to BitGenerator and UniqueReduce

---

scripts/hooks/enforce_boilerplate.py
tests/integration/test_advanced_indexing.py
tests/integration/test_index_routines.py
tests/integration/test_indices.py
tests/integration/test_prod.py
tests/integration/test_reduction.py
tests/integration/test_trace.py
tests/integration/utils/generators.py

Several tests used python's random which will generate different values on a different Legion shards. This violates control replication requirements.

Fix for control replication violation in test 

---

docs/cunumeric/source/developer/building.rst
docs/cunumeric/source/user/installation.rst

cc  @ipdemes @manopapad not sure if we want ot try and re-deploy existing docs or now. The "build" page does exist, just the link from the "install" page was wrong.

fix build instructions link

---

tests/integration/test_random_advanced.py
tests/integration/test_random_beta.py
tests/integration/test_random_bitgenerator.py
tests/integration/test_random_gamma.py
tests/integration/test_random_straightforward.py
tests/integration/test_reshape.py

* Skip advanced RNG not only on MacOS, but any setup that's missing cuRand (e.g. also on CPU installations without the optional host-cuRand component).
* Don't compare arrays created with `np.empty`; they contain uninitialized data, that may be equivalent to `NaN` when
interpreted as a floating-point number, and `np.array_equal` considers that `NaN != NaN`. Fixes a non-deterministic CI failure, see https://github.com/nv-legate/cunumeric/actions/runs/5734924032/job/15544886016.

Various test fixes

---

cunumeric/deferred.py
cunumeric/eager.py
cunumeric/module.py
cunumeric/thunk.py

I introduced this issue with https://github.com/nv-legate/cunumeric/pull/468, because I assumed that `axis : Optional[int] = -1` was just a case of someone misunderstanding `Optional[T]` to mean `T but with a default value`, where actually it means `Union[T, None]`. But actually the NumPy APIs (and the cuNumeric implementations) allow both `None` and `-1`, and just default to `-1`, so the original `Optional[int]` was correct.

Add back None as an accepted value for axis on some type sigs

---

cunumeric/_ufunc/ufunc.py

This change avoids an extraneous warning message, as seen on https://github.com/nv-legate/cunumeric/issues/1009.
Alternatively we could convert explicitly to a NumPy array:
```
if arr.ndim == 0:
scalar_types.append(np.array(orig_arg))
```
but the change on this PR is in line with the `if len(unique_dtypes) == 1 and all_ndarray:` snippet above, which doesn't consider if `cunumeric.ndarray`s are scalars.
Or we could depart from NumPy's semantics altogether, and never consult the actual values of scalars when picking types.
CC @seberg, to advise whether this code could be changed according to recent updates in NumPy's type handling API.

If a scalar ufunc arg is cn.ndarray use its type directly

---

cmake/versions.json
examples/black_scholes.py
examples/cg.py
examples/gemm.py
examples/ingest.py
examples/kmeans.py
examples/kmeans_slow.py
examples/kmeans_sort.py
examples/linreg.py
examples/logreg.py

For testing, this PR points to the PR version of legate.core. Before merge, the version of legate.core should be changed to the commit on the legate.core dev branch.

Update to the latest Legion

---

cunumeric/coverage.py
tests/unit/cunumeric/test_coverage.py

The docstring for numpy.binomial has an unused reference, which causes our doc build to panic in cases where curand is not installed, and thus we end up falling back to numpy for binomial.

Skip the docstrings for functions pulled from cloned modules

---

.pre-commit-config.yaml
cunumeric/array.py
pyproject.toml

This PR updates the `pre-commit` config to use MyPy version 1.5.1 to match the separate MyPy CI job. A new "unused ignore" error is also fixed.

Update pre-commit mypy

---

cunumeric/module.py

In that case the histogram is expected to have floating-point values, and casting those to ints drops information. E.g. this example:
```
import cunumeric as cn
data = cn.arange(20)
hist, _ = cn.histogram(data, density=True)
print(hist)
```
would print out
```
[0 0 0 0 0 0 0 0 0 0]
```
rather than
```
[0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]
```

Don't cast histogram to int64 when density=True

---

src/cunumeric/binary/binary_op_util.h

Fixes a bug reported by @syamajala.
The compile-time result of shifting an `unsigned short` by an `unsigned short` is `int`, so the task body was trying to create an `int` accessor, but the calling side was instantiating an `np.uint16` result array for a shift of a `np.uint16` array by a `np.uint16` value. This resulted in the following code:
```
x = cn.ones((4, 352, 384), dtype=np.uint16)
cn.right_shift(x, 1)
```
failing with an error message like:
```
terminate called after throwing an instance of 'std::invalid_argument'
what():  Type mismatch: int32 accessor to a uint16 store. Disable type checking via accessor template parameter if this is intended.
Signal 6 received by node 0, process 26606 (thread 7f4308670700) - obtaining backtrace
Signal 6 received by process 26606 (thread …
```

Explicitly cast result of shift binary operators

---

cunumeric/array.py
cunumeric/eager.py
cunumeric/module.py
cunumeric/runtime.py
cunumeric/utils.py
tests/integration/test_array.py
tests/integration/test_astype.py
tests/integration/test_atleast_nd.py
tests/integration/test_fill.py
tests/integration/test_fill_diagonal.py
tests/integration/test_logic.py
tests/integration/test_matmul.py
tests/integration/test_repeat.py
tests/integration/test_sort.py
tests/integration/test_split.py
tests/unit/cunumeric/test_utils.py

IMHO there is little value in pretending that we support these types. We currently accept them by falling back to EagerArray, and that works for a little bit, but it is possible that later we will need to convert to a truly Legion-backed implementation, in which case the failure will pop up there.
Instead we should just reject them from the start.

Reject types that DeferredArray doesn't support

---

cunumeric/array.py

NumPy as of 1.25.1 or 1.25.2 removed `np.find_common_type`, and this is causing failures in CI, e.g. https://github.com/nv-legate/cunumeric/pull/593. This PR replaces our last remaining use of this API with `np.result_type`.
Note that the CI on this PR is expected to fail, until https://github.com/nv-legate/cunumeric/pull/1044 is merged.
Also asking @seberg to take a look.

Remove use of deprecated np.find_common_type

---

docs/cunumeric/source/user/index.rst
docs/cunumeric/source/user/practices.rst

This PR adds the "Best Practices" doc authored by @shriram-jagan to the deployed docs User Guide.

Add best practices info to sphinx docs

---

cunumeric/__init__.py
cunumeric/array.py
cunumeric/ma/__init__.py
cunumeric/ma/_masked_array.py

This PR just adds minimal wrapping for the NumPy masked array module. Currently things will just fall back to numpy and emit the fallback warning:
```python
Welcome to Legion Python interactive console
>>> import cunumeric as np
>>> x = np.ma.array(np.matrix([[1, 2], [3, 4]]), mask=[[0, 1], [1, 0]])
/home/bryan/work/cunumeric/cunumeric/coverage.py:186: RuntimeWarning: cuNumeric has not implemented numpy.ma.array and is falling back to canonical NumPy. You may notice significantly decreased performance for this function call.
warnings.warn(
>>> x
masked_matrix(
data=[[1, --],
[--, 4]],
mask=[[False,  True],
[ True, False]],
fill_value=999999)
>>> x.sum()	
/home/bryan/work/cunumeric/cunumeric/coverage.py:186: RuntimeWarning: cuNumeric has not implemented numpy.ma.core.MaskedArray.sum and is …
```

Plumbing for np.ma

---

src/cunumeric/matrix/batched_cholesky_template.inl

The warning was
```
In file included from /Users/mpapadakis/cunumeric/src/cunumeric/matrix/batched_cholesky.cc:19:
/Users/mpapadakis/cunumeric/src/cunumeric/matrix/batched_cholesky_template.inl:82:9: warning: array index -1 is before the beginning of the array [-Warray-bounds]
if (in_strides[DIM - 2] != ncols || in_strides[DIM - 1] != 1) {
^          ~~~~~~~
/Users/mpapadakis/legate.core/src/core/utilities/dispatch.h:34:27: note: in instantiation of function template specialization 'cunumeric::BatchedCholeskyImpl<cunumeric::VariantKind::CPU>::operator()<legate::Type::Code::BOOL, 1>' requested here
return f.template operator()<Type::Code::BOOL, DIM>(std::forward<Fnargs>(args)...);
^
/Users/mpapadakis/cunumeric/src/cunumeric/matrix/batched_cholesky.cc:74:3: note: in instantiation of …
```

Don't instantiate template for low DIM counts, to fix a warning

---

.github/actions/download-artifacts/action.yml
conda/conda-build/meta.yaml

- Constrain cutensor to avoid the new version 2 of cutensor with a changed interface
- add depencies necessary for successful build in newer versions of conda

Update dependencies in meta.yaml

---

install.py

Thread count is not being propagated to Cmake. This fixes that.

Add Cmake flag to ensure we're propagating thread_count

---

cunumeric/linalg/cholesky.py
src/cunumeric/mapper.cc
src/cunumeric/matrix/transpose.cc
src/cunumeric/matrix/transpose.cu
src/cunumeric/matrix/transpose.h
src/cunumeric/matrix/transpose_omp.cc
src/cunumeric/matrix/transpose_template.inl

This was dead code at this point. Fixes https://github.com/nv-legate/cunumeric/pull/1107

Remove logical version of transpose

---

cmake/versions.json
cunumeric/deferred.py
tests/integration/test_overlap.py

Add missing store overlap checks

---

cunumeric/module.py
tests/integration/test_digitize.py

This PR adds support for `np.digitize` 
Numpy has a custom C function to test monotonicity, but that won't work here. Used a simple adjacency compare, but any suggestions for improvement welcome.

Add np.digitize

---

cunumeric/module.py
docs/cunumeric/source/api/io.rst
docs/cunumeric/source/api/routines.rst

Mostly there to ensure that the NumPy ndarray coming out of `np.load` gets cast to a cuNumeric ndarray. As requested by ORNL.

Basic np.load implementation, falling back to NumPy

---

cunumeric/array.py
cunumeric/module.py
docs/cunumeric/source/api/statistics.rst
tests/integration/test_diff.py
tests/integration/test_stats.py

Fitting numpy's cov() implementation into cunumeric's framework

Adding cov() functionality with tests

---

cunumeric/_ufunc/comparison.py
cunumeric/_ufunc/ufunc.py
tests/integration/test_fallback.py
tests/integration/test_logical_reduction.py

Adding logical_and.reduce() functionality by using existing reduction code for products and applying to booleans.

logical_and reduction

---

README.md
docs/cunumeric/source/user/installation.rst

This PR adds a link to the conda docs and also specifies a min conda version to use to ensure that the latest legate versions are properly picked up, and also adds some example output from running an example to verify install.

specify min conda version

---

.github/workflows/gh-build-and-test.yml

We were using runner labels for runners that may not exist anymore.

Fix runners
